$(document).ready(function(event){
 
  $( "[id^=btn]" ).css({"cursor": "pointer"}).click(function() {
  
    const name = $(this).attr("name");
    const type = $(this).attr("type");
    const sex = $(this).attr("sex");
    const side = $(this).attr("side");

    const print = [ ];
    const styleProps = $( this ).css([
      "width", "height", "color", "background-color", "background-image"
    ]);

    $( '[id^="btn"]' ).removeClass('selected');
    $( ".gra-port" ).css({"background-image": "url(./portraits/"+name+".png)"}).removeClass('selected');
    $( ".ico-type" ).css({"background-image": "url(./icons/"+type+".png)"}).removeClass('selected');
    $( ".ico-sex" ).css({"background-image": "url(./icons/"+sex+".png)"}).removeClass('selected');
    $( ".ico-side" ).css({"background-image": "url(./icons/"+side+".png)"}).removeClass('selected');

    $(this).addClass('selected');
    $( ".gra-port" ).css({"background-image": "url(./portraits/"+name+".png)"}).addClass('selected');
    $( ".ico-type" ).css({"background-image": "url(./icons/"+type+".png)"}).addClass('selected');
    $( ".ico-sex" ).css({"background-image": "url(./icons/"+sex+".png)"}).addClass('selected');
    $( ".ico-side" ).css({"background-image": "url(./icons/"+side+".png)"}).addClass('selected');

    const fchar = [], fsuit = [], ftier= [], fname= [], fhei = [], fwei = [], fpot = [], fabil = [];

    $.each(figure, function(idx, obj) {    
      if (name == obj.id) {

        fchar.push( obj.char);
        fsuit.push( obj.suit + " " );
        ftier.push( obj.tier + " " );
        fname.push( obj.name + " " );
        fhei.push( obj.hei + " " );
        fwei.push( obj.wei + " " );
        fpot.push( obj.pot + " " );
        fabil.push( obj.abil + " " );

      }
    }); 

    $(".gra-char").text( fchar );
    $(".info-part-suit").text( fsuit );
    $(".info-part-tier").text( ftier );
    $(".info-part-name").text( fname );
    $(".info-part-hei").text( fhei );
    $(".info-part-wei").text( fwei );
    $(".info-part-pot").text( fpot );
    $(".info-part-abil").text( fabil );

  });
 
    var figure = [

// 컴뱃 영웅
{ id: "hero_agentvenom01", char: "에이전트 베놈", suit: "올뉴, 올디퍼런트", tier: "1", name: "유진 \"플래시\" 톰슨", hei: "188cm", wei: "84kg", pot: "Potential", abil: "Symbiote, Leadership, Agent" },
{ id: "hero_agentvenom01_S01", char: "에이전트 베놈", suit: "에이전트 안티베놈", tier: "1", name: "유진 \"플래시\"톰슨 ", hei: "188cm", wei: "84kg", pot: "Potential", abil: "Symbiote, Leadership, Agent" },
{ id: "hero_amadeuscho01", char: "헐크 (아마데우스 조)", suit: "토탈리 어썸 헐크", tier: "1", name: "아마데우스 조", hei: "변신전 168cm, 변신후 ?cm", wei: "변신전 53kg, 변신후 ?kg", pot: "Potential", abil: "Gamma Radiation, Durability" },
{ id: "hero_amadeuscho01_S01", char: "헐크 (아마데우스 조)", suit: "몬스터 언리쉬드! (MFF 배리언트)", tier: "1", name: "아마데우스 조", hei: "변신전 168cm, 변신후 ?cm", wei: "변신전 53kg, 변신후 ?kg", pot: "Potential", abil: "Gamma Radiation, Durability" },
{ id: "hero_amadeuscho01_S02", char: "헐크 (아마데우스 조)", suit: "브론", tier: "1", name: "아마데우스 조", hei: "변신전 168cm, 변신후 ?cm", wei: "변신전 53kg, 변신후 ?kg", pot: "Potential", abil: "Gamma Radiation, Durability" },
{ id: "hero_americachavez01", char: "아메리카 차베스", suit: "얼티미츠", tier: "1", name: "아메리카 차베스", hei: "183cm", wei: "75kg", pot: "-", abil: "Fast Movement, Strong" },
{ id: "hero_beast01", char: "비스트", suit: "클래식", tier: "1", name: "헨리 \"행크\" 필립 맥코이", hei: "180cm", wei: "182kg", pot: "Potential", abil: "Strong, Agility" },
{ id: "hero_beast01_S01", char: "비스트", suit: "에이지 오브 아포칼립스", tier: "1", name: "헨리 \"행크\" 필립 맥코이", hei: "180cm", wei: "182kg", pot: "Potential", abil: "Strong, Agility" },
{ id: "hero_beast01_S02", char: "비스트", suit: "언캐니 엑스맨", tier: "1", name: "헨리 \"행크\" 필립 맥코이", hei: "180cm", wei: "182kg", pot: "Potential", abil: "Strong, Agility" },
{ id: "hero_blackpanther01", char: "블랙 팬서", suit: "모던", tier: "3", name: "티찰라", hei: "183cm", wei: "90kg", pot: "Potential", abil: "Agility, Command" },
{ id: "hero_blackpanther01_S01", char: "블랙 팬서", suit: "영화 - 캡틴 아메리카: 시빌 워", tier: "3", name: "티찰라", hei: "183cm", wei: "90kg", pot: "Potential", abil: "Agility, Command" },
{ id: "hero_blackpanther01_S02", char: "블랙 팬서", suit: "영화 - 블랙 팬서 1", tier: "3", name: "티찰라", hei: "183cm", wei: "90kg", pot: "Potential", abil: "Agility, Command" },
{ id: "hero_blade01", char: "블레이드", suit: "모던", tier: "1", name: "에릭 브룩스", hei: "188cm", wei: "98kg", pot: "<>", abil: "Healing, Weapon Master" },
{ id: "hero_blade01_S01", char: "블레이드", suit: "70년대 클래식", tier: "1", name: "에릭 브룩스", hei: "188cm", wei: "98kg", pot: "<>", abil: "Healing, Weapon Master" },
{ id: "hero_blade01_S02", char: "블레이드", suit: "어벤져스", tier: "1", name: "에릭 브룩스", hei: "188cm", wei: "98kg", pot: "<>", abil: "Healing, Weapon Master" },
{ id: "hero_captainamerica01", char: "캡틴 아메리카", suit: "영화 - 어벤져스", tier: "3", name: "스티븐 그랜트 \"스티브\" 로저스", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Leadership, Command" },
{ id: "hero_captainamerica01_S01", char: "캡틴 아메리카", suit: "영화 - 어벤져스: 에이지 오브 울트론", tier: "3", name: "스티븐 그랜트 \"스티브\" 로저스", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Leadership, Command" },
{ id: "hero_captainamerica01_S02", char: "캡틴 아메리카", suit: "시크릿 워즈: 2099", tier: "3", name: "스티븐 그랜트 \"스티브\" 로저스", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Leadership, Command" },
{ id: "hero_captainamerica01_S03", char: "캡틴 아메리카", suit: "영화 - 캡틴 아메리카: 윈터 솔져", tier: "3", name: "스티븐 그랜트 \"스티브\" 로저스", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Leadership, Command" },
{ id: "hero_captainamerica01_S04", char: "캡틴 아메리카", suit: "영화 - 캡틴 아메리카: 시빌 워", tier: "3", name: "스티븐 그랜트 \"스티브\" 로저스", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Leadership, Command" },
{ id: "hero_captainamerica01_S05", char: "캡틴 아메리카", suit: "마블 나우!", tier: "3", name: "스티븐 그랜트 \"스티브\" 로저스", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Leadership, Command" },
{ id: "hero_captainamerica01_S06", char: "캡틴 아메리카", suit: "영화 - 어벤져스: 인피니티 워", tier: "3", name: "스티븐 그랜트 \"스티브\" 로저스", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Leadership, Command" },
{ id: "hero_captainamerica01_S07", char: "캡틴 아메리카", suit: "영화 - 어벤져스: 엔드게임", tier: "3", name: "스티븐 그랜트 \"스티브\" 로저스", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Leadership, Command" },
{ id: "hero_captainamerica01_S08", char: "캡틴 아메리카", suit: "영화 - 어벤져스: 엔드게임 (팀 슈트)", tier: "3", name: "스티븐 그랜트 \"스티브\" 로저스", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Leadership, Command" },
{ id: "hero_captainamerica01_S09", char: "캡틴 아메리카", suit: "어벤져스 3099", tier: "3", name: "스티븐 그랜트 \"스티브\" 로저스", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Leadership, Command" },
{ id: "hero_captainamerica01_S10", char: "캡틴 아메리카", suit: "하이드라 슈프림", tier: "3", name: "스티븐 그랜트 \"스티브\" 로저스", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Leadership, Command" },
{ id: "hero_colossus01", char: "콜로서스", suit: "모던", tier: "1", name: "표트르 \"피터\" 니콜라예비치 라스푸틴", hei: "변신전 195cm, 변신후 225cm", wei: "변신전 113kg, 변신후 228kg", pot: "Potential", abil: "Leadership, Strong" },
{ id: "hero_colossus01_S01", char: "콜로서스", suit: "엑스포스", tier: "1", name: "표트르 \"피터\" 니콜라예비치 라스푸틴", hei: "변신전 195cm, 변신후 225cm", wei: "변신전 113kg, 변신후 228kg", pot: "Potential", abil: "Leadership, Strong" },
{ id: "hero_colossus01_S02", char: "콜로서스", suit: "피닉스 파이브", tier: "1", name: "표트르 \"피터\" 니콜라예비치 라스푸틴", hei: "변신전 195cm, 변신후 225cm", wei: "변신전 113kg, 변신후 228kg", pot: "Potential", abil: "Leadership, Strong, 피닉스 포스" },
{ id: "hero_crescent01", char: "크레센트", suit: "모던", tier: "3", name: "단비", hei: "127cm", wei: "27kg", pot: "Potential", abil: "Strong, Durability, Leadership" },
{ id: "hero_crescent01_S01", char: "크레센트", suit: "라이프스타일 시리즈 1", tier: "3", name: "단비", hei: "127cm", wei: "27kg", pot: "Potential", abil: "Strong, Durability, Leadership" },
{ id: "hero_deathlok01", char: "데쓰록", suit: "영화 - 에이전트 오브 쉴.드.", tier: "1", name: "마이클 \"마이크\" 피터슨", hei: "?cm", wei: "?kg", pot: "<>", abil: "Machin, Agent" },
{ id: "hero_deathlok01_S01", char: "데쓰록", suit: "모던", tier: "1", name: "마이클 \"마이크\" 피터슨", hei: "?cm", wei: "?kg", pot: "<>", abil: "Machin, Agent" },
{ id: "hero_drax01", char: "드랙스 더 디스트로이어", suit: "영화 - 가디언즈 오브 갤럭시", tier: "1", name: "과거 아서 샘슨 더글라스", hei: "현재 193cm, 과거 175cm, 강력 224cm", wei: "현재 308kg, 과거 73kg, 강력 476kg", pot: "Potential", abil: "Healing" },
{ id: "hero_drax01_S01", char: "드랙스 더 디스트로이어", suit: "올뉴, 올디퍼런트", tier: "1", name: "과거 아서 샘슨 더글라스", hei: "현재 193cm, 과거 175cm, 강력 224cm", wei: "현재 308kg, 과거 73kg, 강력 476kg", pot: "Potential", abil: "Healing" },
{ id: "hero_giantman01", char: "자이언트맨", suit: "모던", tier: "1", name: "헨리 \"행크\" 조나단 핌", hei: "183cm, 조절", wei: "84kg, 조절", pot: "Potential", abil: "Strong" },
{ id: "hero_giantman01_S01", char: "자이언트맨", suit: "골리앗", tier: "1", name: "헨리 \"행크\" 조나단 핌", hei: "183cm, 조절", wei: "84kg, 조절", pot: "Potential", abil: "Strong" },
{ id: "hero_giantman01_S02", char: "자이언트맨", suit: "울트론 핌", tier: "1", name: "헨리 \"행크\" 조나단 핌", hei: "183cm, 조절", wei: "84kg, 조절", pot: "Potential", abil: "Strong" },
{ id: "hero_gladiator01", char: "글래디에이터", suit: "모던", tier: "2", name: "칼라르크", hei: "198cm", wei: "269kg", pot: "Potential", abil: "Fast Movement, Strong, Leadership" },
{ id: "hero_goliath01", char: "골리앗", suit: "클래식", tier: "1", name: "윌리엄 \"빌\" 바렛 포스터", hei: "183cm, 조절", wei: "90kg, 조절", pot: "Potential", abil: "Durability, Strong" },
{ id: "hero_gorgon01", char: "고르곤", suit: "워 오브 킹즈", tier: "1", name: "고르곤 페트라곤", hei: "200cm", wei: "220kg", pot: "Potential", abil: "Strong" },
{ id: "hero_gorillaman01", char: "고릴라맨", suit: "모던", tier: "1", name: "케니스 \"켄\" 헤일", hei: "183cm", wei: "154kg", pot: "Potential", abil: "Strong, Agility, Weapon Master" },
{ id: "hero_groot01", char: "그루트", suit: "영화 - 가디언즈 오브 갤럭시", tier: "1", name: "그루트", hei: "?cm", wei: "?kg", pot: "Potential", abil: "Healing" },
{ id: "hero_groot01_S01", char: "그루트", suit: "시크릿 워즈: Thors", tier: "1", name: "그루트", hei: "?cm", wei: "?kg", pot: "Potential", abil: "Healing" },
{ id: "hero_groot01_S02", char: "그루트", suit: "영화 - 가디언즈 오브 갤럭시 Vol. 2", tier: "1", name: "그루트", hei: "?cm", wei: "?kg", pot: "Potential", abil: "Healing" },
{ id: "hero_groot01_S03", char: "그루트", suit: "영화 - 어벤져스: 인피니티 워", tier: "1", name: "그루트", hei: "?cm", wei: "?kg", pot: "Potential", abil: "Healing" },
{ id: "hero_hogun01", char: "호군", suit: "모던", tier: "1", name: "호군", hei: "190cm", wei: "304kg", pot: "<>", abil: "Strong" },
{ id: "hero_hulk01", char: "헐크", suit: "영화 - 어벤져스", tier: "3", name: "로버트 브루스 배너", hei: "변신전 177cm, 변신후229cm", wei: "변신전 58kg, 변신후 522kg", pot: "Potential", abil: "Gamma Radiation, Durability" },
{ id: "hero_hulk01_S01", char: "헐크", suit: "시크릿 워즈: 퓨처 임퍼펙트 (마에스트로)", tier: "3", name: "로버트 브루스 배너", hei: "변신전 177cm, 변신후229cm", wei: "변신전 58kg, 변신후 522kg", pot: "Potential", abil: "Gamma Radiation, Durability" },
{ id: "hero_hulk01_S02", char: "헐크", suit: "월드 워 헐크", tier: "3", name: "로버트 브루스 배너", hei: "변신전 177cm, 변신후229cm", wei: "변신전 58kg, 변신후 522kg", pot: "Potential", abil: "Gamma Radiation, Durability" },
{ id: "hero_hulk01_S03", char: "헐크", suit: "영화 - 토르: 라그나로크", tier: "3", name: "로버트 브루스 배너", hei: "변신전 177cm, 변신후229cm", wei: "변신전 58kg, 변신후 522kg", pot: "Potential", abil: "Gamma Radiation, Durability" },
{ id: "hero_hulk01_S04", char: "헐크", suit: "영화 - 어벤져스: 엔드게임", tier: "3", name: "로버트 브루스 배너", hei: "변신전 177cm, 변신후229cm", wei: "변신전 58kg, 변신후 522kg", pot: "Potential", abil: "Gamma Radiation, Durability" },
{ id: "hero_hulk01_S05", char: "헐크", suit: "영화 - 어벤져스: 엔드게임 (팀 슈트)", tier: "3", name: "로버트 브루스 배너", hei: "변신전 177cm, 변신후229cm", wei: "변신전 58kg, 변신후 522kg", pot: "Potential", abil: "Gamma Radiation, Durability" },
{ id: "hero_hulk01_S06", char: "헐크", suit: "이모탈", tier: "3", name: "로버트 브루스 배너", hei: "변신전 177cm, 변신후229cm", wei: "변신전 58kg, 변신후 522kg", pot: "Potential", abil: "Gamma Radiation, Durability" },
{ id: "hero_hulkbuster01", char: "헐크버스터 (마크 44)", suit: "영화 - 어벤져스: 에이지 오브 울트론", tier: "1", name: "아이언 맨의 아머", hei: "335cm", wei: "N/A", pot: "Potential", abil: "Strong, Machine" },
{ id: "hero_hulkbuster01_S01", char: "헐크버스터 (마크 43)", suit: "헤비 듀티 아머", tier: "1", name: "아이언 맨의 아머", hei: "335cm", wei: "N/A", pot: "Potential", abil: "Strong, Machine" },
{ id: "hero_hulkbuster01_S02", char: "헐크버스터 2.0", suit: "영화 - 어벤져스: 인피니티 워", tier: "1", name: "아이언 맨의 아머", hei: "335cm", wei: "N/A", pot: "Potential", abil: "Strong, Machine" },
{ id: "hero_hulkling01", char: "헐클링", suit: "뉴 어벤져스", tier: "1", name: "시어도어 \"테디\" 루퍼스 알트먼 / 도렉 8세", hei: "183cm", wei: "77kg", pot: "Potential", abil: "Strong, Durability" },
{ id: "hero_ironfist01", char: "아이언 피스트", suit: "클래식", tier: "1", name: "다니얼 \"대니\" 토마스 랜드-카이", hei: "180cm", wei: "80kg", pot: "<>", abil: "Agility, Healing" },
{ id: "hero_ironfist01_S01", char: "아이언 피스트", suit: "뉴 어벤져스", tier: "1", name: "다니얼 \"대니\" 토마스 랜드-카이", hei: "180cm", wei: "80kg", pot: "<>", abil: "Agility, Healing" },
{ id: "hero_ironfist01_S02", char: "아이언 피스트", suit: "올뉴, 올디퍼런트", tier: "1", name: "다니얼 \"대니\" 토마스 랜드-카이", hei: "180cm", wei: "80kg", pot: "<>", abil: "Agility, Healing" },
{ id: "hero_ironfist01_S03", char: "아이언 피스트", suit: "드라마 - 아이언 피스트", tier: "1", name: "다니얼 \"대니\" 토마스 랜드-카이", hei: "180cm", wei: "80kg", pot: "<>", abil: "Agility, Healing" },
{ id: "hero_jessicajones01", char: "제시카 존스", suit: "모던", tier: "1", name: "제시카 캠벨 존스", hei: "170cm", wei: "56kg", pot: "-", abil: "Strong, Durability" },
{ id: "hero_kamalakhan01", char: "미즈 마블 (카말라 칸)", suit: "올뉴, 올디퍼런트", tier: "1", name: "카말라 칸", hei: "163cm", wei: "조절", pot: "Potential", abil: "Strong, Healing" },
{ id: "hero_kamalakhan01_S01", char: "미즈 마블 (카말라 칸)", suit: "카라치 코스튬", tier: "1", name: "카말라 칸", hei: "163cm", wei: "조절", pot: "Potential", abil: "Strong, Healing" },
{ id: "hero_kamalakhan01_S02", char: "미즈 마블 (카말라 칸)", suit: "인휴먼즈: 아틸란 라이징", tier: "1", name: "카말라 칸", hei: "163cm", wei: "조절", pot: "Potential", abil: "Strong, Healing" },
{ id: "hero_lukecage01", char: "루크 케이지", suit: "모던", tier: "1", name: "칼 루카스", hei: "198cm", wei: "192kg", pot: "-", abil: "Strong, Durability" },
{ id: "hero_lukecage01_S01", char: "루크 케이지", suit: "올뉴, 올디퍼런트", tier: "1", name: "칼 루카스", hei: "198cm", wei: "192kg", pot: "-", abil: "Strong, Durability" },
{ id: "hero_lukecage01_S02", char: "루크 케이지", suit: "드라마 - 루크 케이지", tier: "1", name: "칼 루카스", hei: "198cm", wei: "191kg", pot: "-", abil: "Strong, Durability" },
{ id: "hero_misterfantastic01", char: "미스터 판타스틱", suit: "모던", tier: "3", name: "리드 리처즈", hei: "186cm", wei: "82kg", pot: "Potential", abil: "Leadership, Durability" },
{ id: "hero_misterfantastic01_S01", char: "미스터 판타스틱", suit: "퓨처 파운데이션", tier: "3", name: "리드 리처즈", hei: "186cm", wei: "82kg", pot: "Potential", abil: "Leadership, Durability" },
{ id: "hero_moonknight01", char: "문 나이트", suit: "모던", tier: "1", name: "마크 스펙터", hei: "188cm", wei: "102kg", pot: "-", abil: "Weapon Master, Leadership" },
{ id: "hero_moonknight01_S01", char: "문 나이트", suit: "아머드", tier: "1", name: "마크 스펙터", hei: "188cm", wei: "102kg", pot: "-", abil: "Weapon Master, Leadership" },
{ id: "hero_moonknight01_S02", char: "문 나이트", suit: "미스터 나이트", tier: "1", name: "마크 스펙터", hei: "188cm", wei: "102kg", pot: "-", abil: "Weapon Master, Leadership" },
{ id: "hero_namor01", char: "네이머 더 서브-마린너", suit: "클래식", tier: "3", name: "네이머 맥켄지", hei: "188cm", wei: "126kg", pot: "Potential", abil: "Strong, Durability" },
{ id: "hero_namor01_S01", char: "네이머 더 서브-마린너", suit: "피닉스 파이브", tier: "3", name: "네이머 맥켄지", hei: "188cm", wei: "126kg", pot: "Potential", abil: "Strong, Durability, 피닉스 Force" },
{ id: "hero_punisher01", char: "퍼니셔", suit: "모던", tier: "1", name: "프랜시스 \"프랭크\" 데이비드 G. 캐슬 / 프랜시스 카스틸리오네", hei: "185cm", wei: "90kg", pot: "Potential", abil: "Leadership, Weapon Master" },
{ id: "hero_punisher01_S01", char: "퍼니셔", suit: "느와르", tier: "1", name: "프랜시스 \"프랭크\" 데이비드 G. 캐슬 / 프랜시스 카스틸리오네", hei: "185cm", wei: "90kg", pot: "Potential", abil: "Leadership, Weapon Master" },
{ id: "hero_punisher01_S02", char: "퍼니셔", suit: "워 저널", tier: "1", name: "프랜시스 \"프랭크\" 데이비드 G. 캐슬 / 프랜시스 카스틸리오네", hei: "185cm", wei: "90kg", pot: "Potential", abil: "Leadership, Weapon Master" },
{ id: "hero_punisher01_S03", char: "퍼니셔", suit: "영화 - 데어데블", tier: "1", name: "프랜시스 \"프랭크\" 데이비드 G. 캐슬 / 프랜시스 카스틸리오네", hei: "185cm", wei: "90kg", pot: "Potential", abil: "Leadership, Weapon Master" },
{ id: "hero_punisher01_S04", char: "퍼니셔", suit: "마블 레거시", tier: "1", name: "프랜시스 \"프랭크\" 데이비드 G. 캐슬 / 프랜시스 카스틸리오네", hei: "185cm", wei: "90kg", pot: "Potential", abil: "Leadership, Weapon Master, Machine" },
{ id: "hero_punisher01_S05", char: "퍼니셔", suit: "코스믹 고스트 라이더", tier: "1", name: "프랜시스 \"프랭크\" 데이비드 G. 캐슬 / 프랜시스 카스틸리오네", hei: "185cm", wei: "90kg", pot: "Potential", abil: "Flame, Power Cosmic" },
{ id: "hero_redshehulk01", char: "레드 쉬헐크", suit: "모던", tier: "1", name: "엘리자베스 \"베티\" 로스", hei: "변신전 168cm, 변신후 200cm", wei: "변신전 50kg, 변신후 317kg", pot: "Potential", abil: "Gamma Radiation, Durability, Flame" },
{ id: "hero_shangchi01", char: "샹치", suit: "모던", tier: "1", name: "상기", hei: "178cm", wei: "79kg", pot: "Potential", abil: "Agility, Leadership" },
{ id: "hero_shehulk01", char: "쉬헐크", suit: "시크릿 워즈: 에이포스", tier: "1", name: "제니퍼 \"젠\" 수잔 월터스", hei: "변신전 178cm, 변신후 201cm", wei: "변신전 64kg, 변신후 295kg", pot: "Potential", abil: "Gamma Radiation, Durability" },
{ id: "hero_shehulk01_S01", char: "쉬헐크", suit: "올뉴, 올디퍼런트", tier: "1", name: "제니퍼 \"젠\" 수잔 월터스", hei: "변신전 178cm, 변신후 201cm", wei: "변신전 64kg, 변신후 295kg", pot: "Potential", abil: "Gamma Radiation, Durability" },
{ id: "hero_shehulk01_S02", char: "쉬헐크", suit: "판타스틱 포", tier: "1", name: "제니퍼 \"젠\" 수잔 월터스", hei: "변신전 178cm, 변신후 201cm", wei: "변신전 64kg, 변신후 295kg", pot: "Potential", abil: "Gamma Radiation, Durability, Fantastic Four" },
{ id: "hero_shehulk01_S03", char: "쉬헐크", suit: "어벤져스", tier: "1", name: "제니퍼 \"젠\" 수잔 월터스", hei: "변신전 178cm, 변신후 201cm", wei: "변신전 64kg, 변신후 295kg", pot: "Potential", abil: "Gamma Radiation, Durability" },
{ id: "hero_sif01", char: "시프", suit: "드라마 - 에이전트 오브 쉴.드.", tier: "1", name: "시프", hei: "188cm", wei: "193kg", pot: "-", abil: "Agility" },
{ id: "hero_sif01_S01", char: "시프", suit: "모던", tier: "1", name: "시프", hei: "188cm", wei: "193kg", pot: "-", abil: "Agility" },
{ id: "hero_swordmaster01", char: "소드 마스터", suit: "모던", tier: "1", name: "린 리에", hei: "175cm", wei: "79kg", pot: "Potential", abil: "Leadership, Weapon Master" },
{ id: "hero_thing01", char: "씽", suit: "모던", tier: "1", name: "벤자민 \"벤\" 제이콥 그림", hei: "183cm", wei: "227kg", pot: "Potential", abil: "Durability, Strong" },
{ id: "hero_thing01_S01", char: "씽", suit: "퓨처 파운데이션", tier: "1", name: "벤자민 \"벤\" 제이콥 그림", hei: "183cm", wei: "227kg", pot: "Potential", abil: "Durability, Strong" },
{ id: "hero_valkyrie01", char: "발키리", suit: "영화 - 토르: 라그나로크", tier: "1", name: "브룬힐데", hei: "190cm", wei: "215kg", pot: "Potential", abil: "Strong" },
{ id: "hero_volstagg01", char: "볼스타그", suit: "모던", tier: "1", name: "볼스타그", hei: "203cm", wei: "646kg", pot: "-", abil: "Durability" },
{ id: "hero_whitetiger01", char: "화이트 타이거", suit: "뉴 어벤져스", tier: "1", name: "에이바 아얄라", hei: "170cm", wei: "59kg", pot: "Potential", abil: "Agility" },
{ id: "hero_wolverine01", char: "울버린", suit: "클래식", tier: "3", name: "제임스 \"로건\" 하울렛", hei: "160cm", wei: "136kg", pot: "Potential", abil: "Healing, Weapon Master" },
{ id: "hero_wolverine01_S01", char: "울버린", suit: "에이지 오브 아포칼립스", tier: "3", name: "제임스 \"로건\" 하울렛", hei: "160cm", wei: "136kg", pot: "Potential", abil: "Healing, Weapon Master" },
{ id: "hero_wolverine01_S02", char: "울버린", suit: "올뉴 마블 나우!", tier: "3", name: "제임스 \"로건\" 하울렛", hei: "160cm", wei: "136kg", pot: "Potential", abil: "Healing, Weapon Master" },
{ id: "hero_wolverine01_S03", char: "울버린", suit: "엑스포스", tier: "3", name: "제임스 \"로건\" 하울렛", hei: "160cm", wei: "136kg", pot: "Potential", abil: "Healing, Weapon Master" },
{ id: "hero_wolverine01_S04", char: "울버린", suit: "하우스 오브 엑스", tier: "3", name: "제임스 \"로건\" 하울렛", hei: "160cm", wei: "136kg", pot: "Potential", abil: "Healing, Weapon Master" },

// 컴뱃 악당
{ id: "sv_abomination01", char: "어보미네이션", suit: "모던", tier: "1", name: "에밀 블론스키", hei: "변신전 178, 변신후 203cm", wei: "변신전 82kg, 변신후 444kg", pot: "Potential", abil: "Gamma Radiation, Durability" },
{ id: "sv_absorbingman01", char: "앱소빙 맨", suit: "모던", tier: "1", name: "칼 \"크러셔\" 크릴", hei: "193cm", wei: "222kg", pot: "<>", abil: "Strong" },
{ id: "sv_apocalypse01", char: "아포칼립스", suit: "에이지 오브 아포칼립스", tier: "3", name: "엔 사바 누르", hei: "213cm", wei: "329kg", pot: "Potential", abil: "Strong, Agility" },
{ id: "sv_apocalypse01_S01", char: "아포칼립스", suit: "메시아 콤플렉스", tier: "3", name: "엔 사바 누르", hei: "213cm", wei: "329kg", pot: "Potential", abil: "Strong, Agility" },
{ id: "sv_bullseye01", char: "불스아이", suit: "모던", tier: "1", name: "레스터", hei: "183cm", wei: "79kg", pot: "Potential", abil: "Weapon Master, Pure Evil" },
{ id: "sv_bullseye01_S01", char: "불스아이", suit: "시크릿 워즈: 1872", tier: "1", name: "레스터", hei: "183cm", wei: "79kg", pot: "Potential", abil: "Weapon Master, Pure Evil" },
{ id: "sv_carnage01", char: "카니지", suit: "올뉴, 올디퍼런트", tier: "1", name: "클리터스 캐서디", hei: "185cm", wei: "86kg", pot: "Potential", abil: "Symbiote, Healing" },
{ id: "sv_crossbones01", char: "크로스본즈", suit: "영화 - 캡틴 아메리카: 시빌 워", tier: "1", name: "브록 럼로우", hei: "192cm", wei: "132kg", pot: "Potential", abil: "Weapon Master" },
{ id: "sv_crossbones01_S01", char: "크로스본즈", suit: "모던", tier: "1", name: "브록 럼로우", hei: "192cm", wei: "132kg", pot: "Potential", abil: "Weapon Master" },
{ id: "sv_crossbones01_S02", char: "크로스본즈", suit: "시크릿 엠파이어", tier: "1", name: "브록 럼로우", hei: "192cm", wei: "132kg", pot: "Potential", abil: "Weapon Master" },
{ id: "sv_doctorminerva01", char: "민-에르바", suit: "모던", tier: "1", name: "민-에르바", hei: "175cm", wei: "62kg", pot: "Potential", abil: "Strong, Durability, Pure Evil" },
{ id: "sv_doctorminerva01_S01", char: "민-에르바", suit: "영화 - 캡틴 마블", tier: "1", name: "민-에르바", hei: "175cm", wei: "62kg", pot: "Potential", abil: "Strong, Durability, Pure Evil" },
{ id: "sv_doctoroctopus01", char: "닥터 옥토버스", suit: "클래식", tier: "1", name: "오토 군터 옥타비우스", hei: "175cm", wei: "111kg", pot: "Potential", abil: "Machine, Durability, Sinister Six" },
{ id: "sv_doctoroctopus01_S01", char: "닥터 옥토버스", suit: "슈피리어 스파이더맨", tier: "1", name: "오토 군터 옥타비우스", hei: "175cm", wei: "111kg", pot: "Potential", abil: "Machine, Heightened Sense, Agility" },
{ id: "sv_doctoroctopus01_S02", char: "닥터 옥토버스", suit: "슈피리어 옥토퍼스", tier: "1", name: "오토 군터 옥타비우스", hei: "175cm", wei: "111kg", pot: "Potential", abil: "Machine, Agility, Sinister Six" },
{ id: "sv_juggernaut01", char: "저거너트", suit: "브라더후드 오브 뮤턴츠", tier: "1", name: "케인 마르코", hei: "290cm", wei: "862kg", pot: "Potential", abil: "Strong, Durability, Pure Evil" },
{ id: "sv_killmonger01", char: "킬몽거", suit: "클래식", tier: "1", name: "에릭 \"킬몽거\" 스티븐스 / 은자카다", hei: "198cm", wei: "102kg", pot: "-", abil: "Strong, Command" },
{ id: "sv_killmonger01_S01", char: "킬몽거", suit: "블랙 팬더", tier: "1", name: "에릭 \"킬몽거\" 스티븐스 / 은자카다", hei: "198cm", wei: "102kg", pot: "-", abil: "Strong, Command" },
{ id: "sv_kingpin01", char: "킹핀", suit: "모던", tier: "1", name: "윌슨 그랜트 피스크", hei: "200cm", wei: "204kg", pot: "Potential", abil: "Strong, Command" },
{ id: "sv_kingpin01_S01", char: "킹핀", suit: "시크릿 워즈: 아머 워즈", tier: "1", name: "윌슨 그랜트 피스크", hei: "200cm", wei: "204kg", pot: "Potential", abil: "Strong, Command, Machine" },
{ id: "sv_lizard01", char: "리자드", suit: "클래식", tier: "1", name: "커티스 \"커트\" 코너스", hei: "변신전 180cm, 변신후 203cm", wei: "변신전 79kg, 변신후 249kg", pot: "Potential", abil: "Healing" },
{ id: "sv_moltenman01", char: "몰튼맨", suit: "영화 - 스파이더맨: 파 프롬 홈", tier: "1", name: "마크 랙스턴", hei: "198cm", wei: "249kg", pot: "Potential", abil: "Pure Evil, Durability, Flame" },
{ id: "sv_morbius01", char: "모비우스 더 리빙 뱀파이어", suit: "모던", tier: "1", name: "마이클 모비우스", hei: "178cm", wei: "77kg", pot: "-", abil: "New" },
{ id: "sv_nebula01", char: "네뷸라", suit: "영화 - 가디언즈 오브 갤럭시", tier: "1", name: "불명", hei: "185cm", wei: "84kg", pot: "Potential", abil: "Shock, Weapon Master" },
{ id: "sv_nebula01_S01", char: "네뷸라", suit: "클래식", tier: "1", name: "불명", hei: "185cm", wei: "84kg", pot: "Potential", abil: "Shock, Weapon Master" },
{ id: "sv_nebula01_S02", char: "네뷸라", suit: "영화 - 어벤져스: 엔드게임", tier: "1", name: "불명", hei: "185cm", wei: "84kg", pot: "Potential", abil: "Shock, Weapon Master" },
{ id: "sv_nebula01_S03", char: "네뷸라", suit: "영화 - 어벤져스: 엔드게임 (팀 슈트)", tier: "1", name: "불명", hei: "185cm", wei: "84kg", pot: "Potential", abil: "Shock, Weapon Master" },
{ id: "sv_redguardian01", char: "레드 가디언", suit: "모던", tier: "1", name: "알렉세이 알라노비치 쇼스타코프", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Strong, Agility" },
{ id: "sv_redguardian01_S01", char: "레드 가디언", suit: "영화 - 블랙 위도우", tier: "1", name: "알렉세이 알라노비치 쇼스타코프", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Strong, Agility" },
{ id: "sv_redhulk01", char: "레드 헐크", suit: "모던", tier: "1", name: "테디어스 E. \"썬더볼트\" 로스", hei: "변신전 185cm,  변신후 213cm", wei: "변신전 111kg, 변신후 544kg", pot: "Potential", abil: "Gamma Radiation, Durability, Flame" },
{ id: "sv_redhulk01_S01", char: "레드 헐크", suit: "마블 나우!", tier: "1", name: "로버트 L. 매버릭", hei: "변신전 185cm,  변신후 213cm", wei: "변신전 111kg, 변신후 544kg", pot: "Potential", abil: "Gamma Radiation, Durability, Flame" },
{ id: "sv_redhulk01_S02", char: "레드 헐크", suit: "복수의 심비오트", tier: "1", name: "테디어스 E. \"썬더볼트\" 로스", hei: "변신전 185cm,  변신후 213cm", wei: "변신전 111kg, 변신후 544kg", pot: "Potential", abil: "Symbiote, Flame" },
{ id: "sv_rhino01", char: "라이노", suit: "클래식", tier: "1", name: "알렉세이 미하일로비치 시체비치", hei: "195cm", wei: "322kg", pot: "Potential", abil: "Durability, Strong" },
{ id: "sv_sabretooth01", char: "세이버투스", suit: "브라더후드 오브 뮤턴츠", tier: "1", name: "빅터 크리드", hei: "201cm", wei: "125kg 아다만티움 170kg", pot: "Potential", abil: "Pure Evil, Agility" },
{ id: "sv_sabretooth01_S01", char: "세이버투스", suit: "언캐니 어벤져스", tier: "1", name: "빅터 크리드", hei: "201cm", wei: "125kg 아다만티움 170kg", pot: "Potential", abil: "Pure Evil, Agility" },
{ id: "sv_sandman01", char: "샌드맨", suit: "클래식", tier: "1", name: "윌리엄 베이커", hei: "185cm", wei: "113kg, 조절", pot: "Potential", abil: "Durability, Sinister Six" },
{ id: "sv_skurge01", char: "스커지 더 엑시큐셔너", suit: "영화 - 토르: 라그나로크", tier: "1", name: "스커지", hei: "218cm", wei: "499kg", pot: "-", abil: "Durability, Strong" },
{ id: "sv_taskmaster01", char: "태스크마스터", suit: "모던", tier: "1", name: "앤서니 \"토니\" 마스터스", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Weapon Master, Pure Evil" },
{ id: "sv_taskmaster01_S01", char: "태스크마스터", suit: "영화 - 블랙 위도우", tier: "1", name: "앤서니 \"토니\" 마스터스", hei: "188cm", wei: "100kg", pot: "Potential", abil: "Weapon Master, Pure Evil" },
{ id: "sv_titania01", char: "티타니아", suit: "모던", tier: "1", name: "매리 맥페란", hei: "198cm", wei: "247kg", pot: "-", abil: "Strong" },
{ id: "sv_ulik01", char: "율리크", suit: "모던", tier: "1", name: "율리크", hei: "193cm", wei: "354kg", pot: "-", abil: "Durability, Strong" },
{ id: "sv_venom01", char: "베놈", suit: "클래식", tier: "1", name: "에드워드 \"에디\" 찰스 앨런 브록", hei: "190cm", wei: "117kg", pot: "-", abil: "Symbiote, Healing" },
{ id: "sv_venom01_S01", char: "베놈", suit: "시크릿 워즈: 마블 좀비스", tier: "1", name: "에드워드 \"에디\" 찰스 앨런 브록", hei: "190cm", wei: "117kg", pot: "-", abil: "Symbiote, Healing" },
{ id: "sv_venom01_S02", char: "베놈", suit: "안티 베놈", tier: "1", name: "에드워드 \"에디\" 찰스 앨런 브록", hei: "190cm", wei: "117kg", pot: "-", abil: "Symbiote, Healing" },

// 스피드 영웅
{ id: "hero_aero01", char: "에어로", suit: "모던", tier: "1", name: "레이 링", hei: "170cm", wei: "54kg", pot: "Potential", abil: "Fast Movement, Leadership" },
{ id: "hero_angel01", char: "엔젤", suit: "클래식", tier: "1", name: "워렌 케네스 워싱턴 3세", hei: "183cm", wei: "68kg", pot: "Potential", abil: "Leadership, Fast Movement" },
{ id: "hero_angel01_S01", char: "엔젤", suit: "엑스포스 (아크엔젤)", tier: "1", name: "워렌 케네스 워싱턴 3세", hei: "183cm", wei: "68kg", pot: "Potential", abil: "Leadership, Fast Movement" },
{ id: "hero_antman01", char: "앤트맨", suit: "모던", tier: "3", name: "스캇 에드워드 해리스 랭", hei: "183cm", wei: "83kg", pot: "Potential", abil: "Agility--" },
{ id: "hero_antman01_S01", char: "앤트맨", suit: "영화 - 앤트맨", tier: "3", name: "스캇 에드워드 해리스 랭", hei: "183cm", wei: "83kg", pot: "Potential", abil: "Agility" },
{ id: "hero_antman01_S02", char: "앤트맨", suit: "영화 - 캡틴 아메리카: 시빌 워", tier: "3", name: "스캇 에드워드 해리스 랭", hei: "183cm", wei: "83kg", pot: "Potential", abil: "Agility" },
{ id: "hero_antman01_S03", char: "앤트맨", suit: "영화 - 앤트맨과 와스프", tier: "3", name: "스캇 에드워드 해리스 랭", hei: "183cm", wei: "83kg", pot: "Potential", abil: "Agility" },
{ id: "hero_antman01_S04", char: "앤트맨", suit: "영화 - 어벤져스: 엔드게임", tier: "3", name: "스캇 에드워드 해리스 랭", hei: "183cm", wei: "83kg", pot: "Potential", abil: "Agility" },
{ id: "hero_antman01_S05", char: "앤트맨", suit: "영화 - 어벤져스: 엔드게임 (팀 슈트)", tier: "3", name: "스캇 에드워드 해리스 랭", hei: "183cm", wei: "83kg", pot: "Potential", abil: "Agility" },
{ id: "hero_arachknight01", char: "아라크나이트", suit: "인피니피 워프", tier: "1", name: "피터 벤자민 파커", hei: "178cm", wei: "76kg", pot: "Potential", abil: "Leadership, Weapon Master, Spider-Sense" },
{ id: "hero_blackcat01", char: "블랙 캣", suit: "모던", tier: "1", name: "펠리시아 사라 하디", hei: "178cm", wei: "54kg", pot: "-", abil: "Agility" },
{ id: "hero_blackcat01_S01", char: "블랙 캣", suit: "클로스", tier: "1", name: "펠리시아 사라 하디", hei: "178cm", wei: "54kg", pot: "-", abil: "Agility" },
{ id: "hero_blackcat01_S02", char: "블랙 캣", suit: "올뉴, 올디퍼런트", tier: "1", name: "펠리시아 사라 하디", hei: "178cm", wei: "54kg", pot: "-", abil: "Agility" },
{ id: "hero_blackwidow01", char: "블랙 위도우", suit: "영화 - 어벤져스", tier: "3", name: "나탈리야 \"나타샤\" 알리야노브나 로마노바", hei: "170cm", wei: "59kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "hero_blackwidow01_S01", char: "블랙 위도우", suit: "영화 - 어벤져스: 에이지 오브 울트론", tier: "3", name: "나탈리야 \"나타샤\" 알리야노브나 로마노바", hei: "170cm", wei: "59kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "hero_blackwidow01_S02", char: "블랙 위도우", suit: "시크릿 워즈: 2099", tier: "3", name: "나탈리야 \"나타샤\" 알리야노브나 로마노바", hei: "170cm", wei: "59kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "hero_blackwidow01_S03", char: "블랙 위도우", suit: "영화 - 캡틴 아메리카: 시빌 워", tier: "3", name: "나탈리야 \"나타샤\" 알리야노브나 로마노바", hei: "170cm", wei: "59kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "hero_blackwidow01_S04", char: "블랙 위도우", suit: "영화 - 어벤져스: 인피니티 워", tier: "3", name: "나탈리야 \"나타샤\" 알리야노브나 로마노바", hei: "170cm", wei: "59kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "hero_blackwidow01_S05", char: "블랙 위도우", suit: "영화 - 어벤져스: 엔드게임", tier: "3", name: "나탈리야 \"나타샤\" 알리야노브나 로마노바", hei: "170cm", wei: "59kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "hero_blackwidow01_S06", char: "블랙 위도우", suit: "영화 - 어벤져스: 엔드게임 (팀 슈트)", tier: "3", name: "나탈리야 \"나타샤\" 알리야노브나 로마노바", hei: "170cm", wei: "59kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "hero_blackwidow01_S07", char: "블랙 위도우", suit: "어벤져스 3099", tier: "3", name: "나탈리야 \"나타샤\" 알리야노브나 로마노바", hei: "170cm", wei: "59kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "hero_blackwidow01_S08", char: "블랙 위도우", suit: "영화 - 블랙 위도우", tier: "3", name: "나탈리야 \"나타샤\" 알리야노브나 로마노바", hei: "170cm", wei: "59kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "hero_blackwidow01_S09", char: "블랙 위도우", suit: "영화 - 블랙 위도우 (스노우 슈트)", tier: "3", name: "나탈리야 \"나타샤\" 알리야노브나 로마노바", hei: "170cm", wei: "59kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "hero_daredevil01", char: "데어데블", suit: "모던", tier: "1", name: "매튜 \"맷\" 마이클 머독", hei: "183cm", wei: "90kg", pot: "Potential", abil: "Heightened Senses, Agility, Leadership" },
{ id: "hero_daredevil01_S01", char: "데어데블", suit: "드라마: 데빌 오브 헬스 키친", tier: "1", name: "매튜 \"맷\" 마이클 머독", hei: "183cm", wei: "90kg", pot: "Potential", abil: "Heightened Senses, Agility, Leadership" },
{ id: "hero_daredevil01_S02", char: "데어데블", suit: "올뉴, 올디퍼런트", tier: "1", name: "매튜 \"맷\" 마이클 머독", hei: "183cm", wei: "90kg", pot: "Potential", abil: "Heightened Senses, Agility, Leadership" },
{ id: "hero_darkhawk01", char: "다크호크", suit: "모던", tier: "1", name: "크리스토퍼 \"크리스\" 파웰", hei: "175cm", wei: "68kg", pot: "Potential", abil: "Leadership, Fast Movement" },
{ id: "hero_deadpool01", char: "데드풀", suit: "모던", tier: "3", name: "웨이드 윌슨", hei: "188cm", wei: "95kg", pot: "Potential", abil: "Weapon Master, Healing" },
{ id: "hero_deadpool01_S01", char: "데드풀", suit: "엑스포스", tier: "3", name: "웨이드 윌슨", hei: "188cm", wei: "95kg", pot: "Potential", abil: "Weapon Master, Healing" },
{ id: "hero_deadpool01_S02", char: "데드풀", suit: "레이디 데드풀", tier: "3", name: "웨이드 윌슨", hei: "188cm", wei: "95kg", pot: "Potential", abil: "Weapon Master, Healing" },
{ id: "hero_deadpool01_S03", char: "데드풀", suit: "레이디 데드풀 홀리데이 파티", tier: "3", name: "웨이드 윌슨", hei: "188cm", wei: "95kg", pot: "Potential", abil: "Weapon Master, Healing" },
{ id: "hero_domino01", char: "도미노", suit: "엑스포스", tier: "1", name: "니나 서먼", hei: "173cm", wei: "54kg", pot: "Potential", abil: "Weapon Maste, rAgility" },
{ id: "hero_domino01_S01", char: "도미노", suit: "마블 나우!", tier: "1", name: "니나 서먼", hei: "173cm", wei: "54kg", pot: "Potential", abil: "Weapon Master, Agility" },
{ id: "hero_elektra01", char: "엘렉트라", suit: "클래식", tier: "1", name: "엘렉트라 나치오스", hei: "175cm", wei: "59kg", pot: "-", abil: "Weapon Master" },
{ id: "hero_elektra01_S01", char: "엘렉트라", suit: "드라마 - 데어데블", tier: "1", name: "엘렉트라 나치오스", hei: "175cm", wei: "59kg", pot: "-", abil: "Weapon Master" },
{ id: "hero_elsabloodstone01", char: "엘사 블러드스톤", suit: "모던", tier: "1", name: "엘사 블러드스톤", hei: "175cm", wei: "54kg", pot: "-", abil: "Weapon Master" },
{ id: "hero_elsabloodstone01_S01", char: "엘사 블러드스톤", suit: "시크릿 워즈: 마블 좀비스", tier: "1", name: "엘사 블러드스톤", hei: "175cm", wei: "54kg", pot: "-", abil: "Weapon Master" },
{ id: "hero_elsabloodstone01_S02", char: "엘사 블러드스톤", suit: "몬스터 언리쉬드! (MFF 배리언트)", tier: "1", name: "엘사 블러드스톤", hei: "175cm", wei: "54kg", pot: "-", abil: "Weapon Master" },
{ id: "hero_falcon01", char: "팔콘", suit: "영화 - 캡틴 아메리카: 윈터 솔져", tier: "1", name: "사무엘 \"샘\" 토마스 윌슨", hei: "188cm", wei: "109kg", pot: "Potential", abil: "Fast Movement, Leadership" },
{ id: "hero_falcon01_S01", char: "팔콘", suit: "올뉴 캡틴 아메리카", tier: "1", name: "사무엘 \"샘\" 토마스 윌슨", hei: "188cm", wei: "109kg", pot: "Potential", abil: "Fast Movement, Leadership" },
{ id: "hero_falcon01_S02", char: "팔콘", suit: "영화 - 캡틴 아메리카: 시빌 워", tier: "1", name: "사무엘 \"샘\" 토마스 윌슨", hei: "188cm", wei: "109kg", pot: "Potential", abil: "Fast Movement, Leadership" },
{ id: "hero_falcon01_S03", char: "팔콘", suit: "마블 레거시", tier: "1", name: "사무엘 \"샘\" 토마스 윌슨", hei: "188cm", wei: "109kg", pot: "Potential", abil: "Fast Movement, Leadership" },
{ id: "hero_fandral01", char: "판드랄", suit: "모던", tier: "1", name: "판드랄", hei: "193cm", wei: "265kg", pot: "-", abil: "Agility" },
{ id: "hero_fantomex01", char: "판토멕스", suit: "엑스포스", tier: "1", name: "찰리 클러스터-7", hei: "175cm", wei: "79kg", pot: "Potential", abil: "Weapon Master, Agility" },
{ id: "hero_gamora01", char: "가모라", suit: "영화 - 가디언즈 오브 갤럭시", tier: "1", name: "가모라", hei: "183cm", wei: "77kg", pot: "Potential", abil: "Agility, Weapon Master" },
{ id: "hero_gamora01_S01", char: "가모라", suit: "올뉴, 올디퍼런트", tier: "1", name: "가모라", hei: "183cm", wei: "77kg", pot: "Potential", abil: "Agility, Weapon Master" },
{ id: "hero_gamora01_S02", char: "가모라", suit: "영화 - 가디언즈 오브 갤럭시 Vol. 2", tier: "1", name: "가모라", hei: "183cm", wei: "77kg", pot: "Potential", abil: "Agility, Weapon Master" },
{ id: "hero_gwenpool01", char: "그웬풀", suit: "올뉴, 올디퍼런트", tier: "1", name: "그웬 풀", hei: "170cm", wei: "59kg", pot: "-", abil: "Agility" },
{ id: "hero_gwenpool01_S01", char: "그웬풀", suit: "그웬 풀", tier: "1", name: "그웬 풀", hei: "170cm", wei: "59kg", pot: "-", abil: "Agility" },
{ id: "hero_gwenpool01_S02", char: "그웬풀", suit: "홀리데이 파티", tier: "1", name: "그웬 풀", hei: "170cm", wei: "59kg", pot: "-", abil: "Agility" },
{ id: "hero_hawkeye01", char: "호크아이", suit: "영화 - 어벤져스", tier: "1", name: "클린턴 \"클린트\" 프랜시스 바턴", hei: "190cm", wei: "104kg", pot: "Potential", abil: "Agent, Weapon Master" },
{ id: "hero_hawkeye01_S01", char: "호크아이", suit: "영화 - 어벤져스: 에이지 오브 울트론", tier: "1", name: "클린턴 \"클린트\" 프랜시스 바턴", hei: "190cm", wei: "104kg", pot: "Potential", abil: "Agent, Weapon Master" },
{ id: "hero_hawkeye01_S02", char: "호크아이", suit: "영화 - 캡틴 아메리카: 시빌 워", tier: "1", name: "클린턴 \"클린트\" 프랜시스 바턴", hei: "190cm", wei: "104kg", pot: "Potential", abil: "Agent, Weapon Master" },
{ id: "hero_hawkeye01_S03", char: "호크아이", suit: "클래식", tier: "1", name: "클린턴 \"클린트\" 프랜시스 바턴", hei: "190cm", wei: "104kg", pot: "Potential", abil: "Agent, Weapon Master" },
{ id: "hero_hawkeye01_S04", char: "호크아이", suit: "영화 - 어벤져스: 엔드게임 (로닌)", tier: "1", name: "클린턴 \"클린트\" 프랜시스 바턴", hei: "190cm", wei: "104kg", pot: "Potential", abil: "Agent, Weapon Master" },
{ id: "hero_hellcat01", char: "헬캣", suit: "올뉴, 올디퍼런트", tier: "1", name: "패트리샤 \"팻시\" 트리시 워커", hei: "173cm", wei: "61kg", pot: "-", abil: "Agility" },
{ id: "hero_katebishop01", char: "호크아이 (케이트 비숍)", suit: "마블 나우!", tier: "1", name: "캐서린 \"케이트\" 엘리자베스 비숍", hei: "165cm", wei: "54kg", pot: "-", abil: "Agent, Agility" },
{ id: "hero_karnak01", char: "카르낙", suit: "워 오브 킹즈", tier: "1", name: "카르낙 만데르-아주르", hei: "170cm", wei: "68kg", pot: "Potential", abil: "Heightened Senses" },
{ id: "hero_karnak01_S01", char: "카르낙", suit: "올뉴, 올디퍼런트", tier: "1", name: "카르낙 만데르-아주르", hei: "170cm", wei: "68kg", pot: "Potential", abil: "Heightened Senses" },
{ id: "hero_kidkaiju01", char: "키드 카이쥬", suit: "몬스터 언리쉬드!", tier: "1", name: "케이 카와데", hei: "132cm", wei: "36kg", pot: "-", abil: "Command" },
{ id: "hero_kidkaiju01_S01", char: "키드 카이쥬", suit: "몬스터 언리쉬드! (MFF 배리언트)", tier: "1", name: "케이 카와데", hei: "132cm", wei: "36kg", pot: "-", abil: "Command" },
{ id: "hero_kittypryde01", char: "키티 프라이드", suit: "모던", tier: "1", name: "캐서린 \"키티\" 앤 프라이드", hei: "167cm", wei: "50kg", pot: "Potential", abil: "Command, Weapon Master" },
{ id: "hero_lunasnow01", char: "루나 스노우", suit: "모던", tier: "3", name: "설희", hei: "170cm", wei: "54kg", pot: "Potential", abil: "Cold Blooded, Leadership" },
{ id: "hero_lunasnow01_S01", char: "루나 스노우", suit: "안드로메다 슈트", tier: "3", name: "설희", hei: "170cm", wei: "54kg", pot: "Potential", abil: "Cold Blooded, Leadership" },
{ id: "hero_lunasnow01_S02", char: "루나 스노우", suit: "라이프스타일 시리즈 1", tier: "3", name: "설희", hei: "170cm", wei: "54kg", pot: "Potential", abil: "Cold Blooded, Leadership" },
{ id: "hero_mistyknight01", char: "미스티 나이트", suit: "올뉴, 올디퍼런트", tier: "1", name: "머세이디스 켈리 \"미스티\" 나이트", hei: "175cm", wei: "62kg", pot: "-", abil: "Weapon Master, Agent" },
{ id: "hero_mockingbird01", char: "모킹버드", suit: "영웅 시대", tier: "1", name: "바바라 \"바비\" 모스", hei: "175cm", wei: "61kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "hero_mockingbird01_S01", char: "모킹버드", suit: "영화 - 에이전트 오브 쉴.드. (바비 모스)", tier: "1", name: "바바라 \"바비\" 모스", hei: "175cm", wei: "61kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "hero_mockingbird01_S02", char: "모킹버드", suit: "모던", tier: "1", name: "바바라 \"바비\" 모스", hei: "175cm", wei: "61kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "hero_nickfury01", char: "닉 퓨리", suit: "모던", tier: "1", name: "니콜라스 \"닉\" 조셉 퓨리", hei: "190cm", wei: "95kg", pot: "Potential", abil: "Agent, Leadership, Weapon Master" },
{ id: "hero_nickfury01_S01", char: "닉 퓨리", suit: "영화 - 캡틴 마블", tier: "1", name: "니콜라스 \"닉\" 조셉 퓨리", hei: "190cm", wei: "95kg", pot: "Potential", abil: "Agent, Leadership, Weapon Master" },
{ id: "hero_nightcrawler01", char: "나이트크롤러", suit: "모던", tier: "1", name: "커트 와그너", hei: "180cm", wei: "73kg", pot: "Potential", abil: "Agility, Leadership" },
{ id: "hero_nightcrawler01_S01", char: "나이트크롤러", suit: "엑스포스", tier: "1", name: "커트 와그너", hei: "180cm", wei: "73kg", pot: "Potential", abil: "Agility, Leadership" },
{ id: "hero_quicksilver01", char: "퀵실버", suit: "클래식", tier: "3", name: "피에트로 장고 막시모프", hei: "183cm", wei: "79kg", pot: "Potential", abil: "Agility, Fast Movement" },
{ id: "hero_quicksilver01_S01", char: "퀵실버", suit: "마블 레거시", tier: "3", name: "피에트로 장고 막시모프", hei: "183cm", wei: "79kg", pot: "Potential", abil: "Agility, Fast Movement" },
{ id: "hero_quicksilver01_S02", char: "퀵실버", suit: "언캐니 어벤져스", tier: "3", name: "피에트로 장고 막시모프", hei: "183cm", wei: "79kg", pot: "Potential", abil: "Agility, Fast Movement" },
{ id: "hero_rogue01", char: "로그", suit: "클래식", tier: "1", name: "앤 마리 단칸토", hei: "173cm", wei: "54kg", pot: "Potential", abil: "Healing, Fast Movement" },
{ id: "hero_rogue01_S01", char: "로그", suit: "에이지 오브 아포칼립스", tier: "1", name: "앤 마리 단칸토", hei: "173cm", wei: "54kg", pot: "Potential", abil: "Healing, Fast Movement" },
{ id: "hero_rogue01_S02", char: "로그", suit: "언캐니 어벤져스", tier: "1", name: "앤 마리 단칸토", hei: "173cm", wei: "54kg", pot: "Potential", abil: "Healing, Fast Movement" },
{ id: "hero_scarletspider01", char: "스칼렛 스파이더", suit: "모던", tier: "1", name: "벤자민 \"벤\" 라일리", hei: "178cm", wei: "75kg", pot: "1", abil: "New" },
{ id: "hero_sharoncarter01", char: "에이전트 13", suit: "모던", tier: "1", name: "샤론 카터", hei: "173cm", wei: "61kg", pot: "Potential", abil: "Agent" },
{ id: "hero_sharoncarter01_S01", char: "에이전트 13", suit: "영화 - 캡틴 아메리카: 시빌 워", tier: "1", name: "샤론 카터", hei: "173cm", wei: "61kg", pot: "Potential", abil: "Agent" },
{ id: "hero_shuri01", char: "슈리", suit: "마블 레거시", tier: "1", name: "슈리", hei: "170cm", wei: "57kg", pot: "Potential", abil: "Heightened Senses--" },
{ id: "hero_shuri01_S01", char: "슈리", suit: "영화 - 블랙 팬서", tier: "1", name: "슈리", hei: "170cm", wei: "57kg", pot: "Potential", abil: "LeadershipHeightened Senses-" },
{ id: "hero_silk01", char: "실크", suit: "올뉴, 올디퍼런트", tier: "1", name: "신디 문", hei: "170cm", wei: "59kg", pot: "Potential", abil: "Spider-Sense, Agility" },
{ id: "hero_silk01_S01", char: "실크", suit: "웹 슈트", tier: "1", name: "신디 문", hei: "170cm", wei: "59kg", pot: "Potential", abil: "Spider-Sense, Agility" },
{ id: "hero_spidergwen01", char: "스파이더 그웬", suit: "올뉴, 올디퍼런트", tier: "1", name: "그웬돌린 \"그웬\" 맥신 스테이시", hei: "165cm", wei: "57kg", pot: "-", abil: "Spider-Sense, Agility, Leadership" },
{ id: "hero_spidergwen01_S01", char: "스파이더 그웬", suit: "그웬돌린 스테이시", tier: "1", name: "그웬돌린 \"그웬\" 맥신 스테이시", hei: "165cm", wei: "57kg", pot: "-", abil: "Spider-Sense, Agility, Leadership" },
{ id: "hero_spiderman01", char: "스파이더맨", suit: "클래식", tier: "3", name: "피터 벤자민 파커", hei: "178cm", wei: "76kg", pot: "Potential", abil: "Spider-Sense, Leadership, Agility" },
{ id: "hero_spiderman01_S01", char: "스파이더맨", suit: "시크릿 워즈: 리뉴 유어 바우", tier: "3", name: "피터 벤자민 파커", hei: "178cm", wei: "76kg", pot: "Potential", abil: "Spider-Sense, Leadership, Agility" },
{ id: "hero_spiderman01_S02", char: "스파이더맨", suit: "올뉴, 올디퍼런트", tier: "3", name: "피터 벤자민 파커", hei: "178cm", wei: "76kg", pot: "Potential", abil: "Spider-Sense, Leadership, Agility" },
{ id: "hero_spiderman01_S03", char: "스파이더맨", suit: "영화 - 캡틴 아메리카: 시빌 워", tier: "3", name: "피터 벤자민 파커", hei: "178cm", wei: "76kg", pot: "Potential", abil: "Spider-Sense, Leadership, Agility" },
{ id: "hero_spiderman01_S04", char: "스파이더맨", suit: "영화 - 스파이더맨: 홈커밍 (홈메이드 슈트)", tier: "3", name: "피터 벤자민 파커", hei: "178cm", wei: "76kg", pot: "Potential", abil: "Spider-Sense, Leadership, Agility" },
{ id: "hero_spiderman01_S05", char: "스파이더맨", suit: "영화 - 어벤져스: 인피니티 워", tier: "3", name: "피터 벤자민 파커", hei: "178cm", wei: "76kg", pot: "Potential", abil: "Spider-Sense, Leadership, Agility" },
{ id: "hero_spiderman01_S06", char: "스파이더맨", suit: "영화 - 스파이더맨: 파 프롬 홈", tier: "3", name: "피터 벤자민 파커", hei: "178cm", wei: "76kg", pot: "Potential", abil: "Spider-Sense, Leadership, Agility" },
{ id: "hero_spiderman01_S07", char: "스파이더맨", suit: "영화 - 스파이더맨: 파 프롬 홈 (스텔스 슈트)", tier: "3", name: "피터 벤자민 파커", hei: "178cm", wei: "76kg", pot: "Potential", abil: "Spider-Sense, Leadership, Agility" },
{ id: "hero_milesmorales01", char: "스파이더맨 (마일즈 모랄레스)", suit: "올뉴, 올디퍼런트", tier: "1", name: "마일즈 곤살로 모랄레스", hei: "157cm", wei: "57kg", pot: "Potential", abil: "Spider-Sense, Agility, Leadership" },
{ id: "hero_milesmorales01_S01", char: "스파이더맨 (마일즈 모랄레스)", suit: "인투 더 스파이더버스", tier: "1", name: "마일즈 곤살로 모랄레스", hei: "157cm", wei: "57kg", pot: "Potential", abil: "Spider-Sense, Agility, Leadership" },
{ id: "hero_spiderman209901", char: "스파이더맨 2099", suit: "모던", tier: "1", name: "미구엘 오하라", hei: "178cm", wei: "77kg", pot: "Potential", abil: "Spider-Sense, Leadership, Agility" },
{ id: "hero_spiderman209901_S01", char: "스파이더맨 2099", suit: "올뉴, 올디퍼런트", tier: "1", name: "미구엘 오하라", hei: "178cm", wei: "77kg", pot: "Potential", abil: "Spider-Sense, Leadership, Agility" },
{ id: "hero_squirrelgirl01", char: "스쿼럴 걸", suit: "뉴 어벤져스", tier: "1", name: "도린 알렌 그린", hei: "160cm", wei: "45kg", pot: "Potential", abil: "Agility" },
{ id: "hero_squirrelgirl01_S01", char: "스쿼럴 걸", suit: "마블 나우!", tier: "1", name: "도린 알렌 그린", hei: "160cm", wei: "45kg", pot: "Potential", abil: "Agility" },
{ id: "hero_sunbird01", char: "썬 버드", suit: "모던", tier: "1", name: "불명", hei: "187cm", wei: "84kg", pot: "Potential", abil: "Flame, Agility" },
{ id: "hero_wave01", char: "웨이브", suit: "모던", tier: "1", name: "펄 팡안", hei: "167cm", wei: "61kg", pot: "Potential", abil: "Heightened Senses, Agility" },
{ id: "hero_whitefox01", char: "화이트 폭스", suit: "모던", tier: "1", name: "한아미", hei: "178cm", wei: "54kg", pot: "Potential", abil: "Leadership, Agility" },
{ id: "hero_whitefox01_S01", char: "화이트 폭스", suit: "라이프스타일 시리즈 1", tier: "1", name: "한아미", hei: "178cm", wei: "54kg", pot: "Potential", abil: "Leadership, Agility" },
{ id: "hero_wintersoldier01", char: "윈터 솔져", suit: "영화 - 캡틴 아메리카: 윈터 솔져", tier: "3", name: "제임스 뷰캐넌 \"버키\" 반즈", hei: "175cm", wei: "117kg", pot: "Potential", abil: "Weapon Master" },
{ id: "hero_wintersoldier01_S01", char: "윈터 솔져", suit: "영화 - 캡틴 아메리카: 시빌 워", tier: "3", name: "제임스 뷰캐넌 \"버키\" 반즈", hei: "175cm", wei: "117kg", pot: "Potential", abil: "Weapon Master" },
{ id: "hero_wintersoldier01_S02", char: "윈터 솔져", suit: "캡틴 아메리카", tier: "3", name: "제임스 뷰캐넌 \"버키\" 반즈", hei: "175cm", wei: "117kg", pot: "Potential", abil: "Weapon Master" },
{ id: "hero_wintersoldier01_S03", char: "윈터 솔져", suit: "영화 - 어벤져스: 인피니티 워", tier: "3", name: "제임스 뷰캐넌 \"버키\" 반즈", hei: "175cm", wei: "177kg", pot: "Potential", abil: "Weapon Master" },
{ id: "hero_wong01", char: "웡", suit: "올뉴, 올디퍼런트", tier: "1", name: "웡", hei: "173cm", wei: "63kg", pot: "Potential", abil: "Weapon Master" },
{ id: "hero_wong01_S01", char: "웡", suit: "영화 - 닥터 스트레인지", tier: "1", name: "웡", hei: "173cm", wei: "63kg", pot: "Potential", abil: "Weapon Master" },
{ id: "hero_x-2301", char: "X-23", suit: "클래식", tier: "1", name: "로라 키니", hei: "155cm", wei: "50kg", pot: "Potential", abil: "Healing, Agility" },
{ id: "hero_x-2301_S01", char: "X-23", suit: "엑스포스", tier: "1", name: "로라 키니", hei: "155cm", wei: "50kg", pot: "Potential", abil: "Healing, Agility" },

// 스피드 악당
{ id: "sv_baronzemo01", char: "제모 남작", suit: "모던", tier: "1", name: "헬무트 J. 제모", hei: "178cm", wei: "83kg", pot: "Potential", abil: "Agility, Pure Evil" },
{ id: "sv_electro01", char: "일렉트로", suit: "모던", tier: "1", name: "맥스웰 \"맥스\" 딜런", hei: "180cm", wei: "75kg", pot: "Potential", abil: "Pure Evil, Shock, Sinister Six" },
{ id: "sv_ghost01", char: "고스트", suit: "모던", tier: "1", name: "불명", hei: "180cm", wei: "79kg", pot: "Potential", abil: "Machine, Weapon Master" },
{ id: "sv_ghost01_S01", char: "고스트", suit: "영화 - 앤트맨과 와스프", tier: "1", name: "에이바 스타", hei: "167cm", wei: "55kg", pot: "Potential", abil: "Machine, Weapon Master" },
{ id: "sv_greengoblin01", char: "그린 고블린", suit: "클래식", tier: "1", name: "노먼 버질 오스본", hei: "180cm", wei: "84kg", pot: "Potential", abil: "Fast Movement, Poison" },
{ id: "sv_greengoblin01_S01", char: "그린 고블린", suit: "얼티밋", tier: "1", name: "노먼 버질 오스본", hei: "?cm", wei: "?kg", pot: "Potential", abil: "Fast Movement, Flame" },
{ id: "sv_korath01", char: "코라스 더 퍼수어", suit: "영화 - 캡틴 마블", tier: "1", name: "코라스", hei: "183cm", wei: "131kg", pot: "Potential", abil: "Pure Evil, Weapon Master" },
{ id: "sv_kraventhehunter01", char: "크레이븐 더 헌터", suit: "모던", tier: "1", name: "세르게이 니콜라예비치 크라비노프", hei: "183cm", wei: "107kg", pot: "Potential", abil: "Agility, Weapon Master, Sinister Six" },
{ id: "sv_mystique01", char: "미스틱", suit: "모던", tier: "1", name: "레이븐 다크홈", hei: "178cm", wei: "54kg", pot: "Potential", abil: "Agility, Weapon Master" },
{ id: "sv_sin01", char: "신", suit: "올뉴, 올디퍼런트", tier: "1", name: "신시아 \"신\" 슈미트", hei: "165cm", wei: "51kg", pot: "Potential", abil: "Pure Evil, Weapon Master" },
{ id: "sv_viper01", char: "바이퍼", suit: "모던", tier: "1", name: "오펠리아 사르키샨", hei: "175cm", wei: "63kg", pot: "Potential", abil: "Poison, Pure Evil" },
{ id: "sv_vulture01", char: "벌쳐", suit: "클래식", tier: "1", name: "아드리안 툼즈", hei: "180cm", wei: "79kg", pot: "Potential", abil: "Agility, Fast Movement, Sinister Six" },
{ id: "sv_vulture01_S01", char: "벌쳐", suit: "영화 - 스파이더맨: 홈커밍", tier: "1", name: "아드리안 툼즈", hei: "180cm", wei: "79kg", pot: "Potential", abil: "Agility, Fast Movement, Sinister Six" },
{ id: "sv_yelenabelova01", char: "옐레나 벨로바", suit: "모던", tier: "1", name: "옐레나 벨로바", hei: "170cm", wei: "61kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "sv_yelenabelova01_S01", char: "옐레나 벨로바", suit: "영화 - 블랙 위도우", tier: "1", name: "옐레나 벨로바", hei: "170cm", wei: "61kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "sv_yelenabelova01_S02", char: "옐레나 벨로바", suit: "영화 - 블랙 위도우 (스노우 슈트)", tier: "1", name: "옐레나 벨로바", hei: "170cm", wei: "61kg", pot: "Potential", abil: "Agent, Agility" },
{ id: "sv_yondu01", char: "욘두", suit: "영화 - 가디언즈 오브 갤럭시", tier: "1", name: "욘두 우돈타", hei: "188cm, 크레스트 포함 216cm", wei: "95kg", pot: "-", abil: "Command, Weapon Master" },
{ id: "sv_yondu01_S01", char: "욘두", suit: "올뉴, 올디퍼런트", tier: "1", name: "욘두 우돈타", hei: "188cm, 크레스트 포함 216cm", wei: "95kg", pot: "-", abil: "Command, Weapon Master" },
{ id: "sv_yondu01_S02", char: "욘두", suit: "영화 - 가디언즈 오브 갤럭시 Vol. 2", tier: "1", name: "욘두 우돈타", hei: "188cm, 크레스트 포함 216cm", wei: "95kg", pot: "-", abil: "Command, Weapon Master" },

// 블라스트 영웅
{ id: "hero_adamwarlock01", char: "센트리", suit: "모던", tier: "2", name: "아담 워록", hei: "188cm", wei: "110kg", pot: "-", abil: "Magic, Time Freezing Immunity" },
{ id: "hero_ancientone01", char: "에인션트 원", suit: "모던", tier: "1", name: "야오", hei: "180cm", wei: "73kg", pot: "Potential", abil: "Magic, Leadership" },
{ id: "hero_ancientone01_S01", char: "에인션트 원", suit: "영화 - 닥터 스트레인지", tier: "1", name: "불명", hei: "cm", wei: "kg", pot: "Potential", abil: "Magic, Leadership" },
{ id: "hero_bishop01", char: "비숍", suit: "디스어셈블드", tier: "1", name: "루카스 비숍", hei: "198cm", wei: "125kg", pot: "Potential", abil: "Energy Projection" },
{ id: "hero_bluedragon01", char: "블루 드래곤", suit: "모던", tier: "1", name: "불명", hei: "177cm", wei: "65kg", pot: "Potential", abil: "Leadership, Shock" },
{ id: "hero_cable01", char: "케이블", suit: "모던", tier: "1", name: "네이슨 크리스토퍼 찰스 서머스", hei: "203cm", wei: "159kg", pot: "Potential", abil: "LeadershipWeapon, Master-" },
{ id: "hero_cable01_S01", char: "케이블", suit: "엑스포스", tier: "1", name: "네이슨 크리스토퍼 찰스 서머스", hei: "203cm", wei: "159kg", pot: "Potential", abil: "Leadership, Weapon Master" },
{ id: "hero_cable01_S02", char: "케이블", suit: "케이블과 데드풀", tier: "1", name: "네이슨 크리스토퍼 찰스 서머스", hei: "203cm", wei: "159kg", pot: "Potential", abil: "Leadership, Weapon Master" },
{ id: "hero_cable01_S03", char: "케이블", suit: "섬머 데이즈", tier: "1", name: "네이슨 크리스토퍼 찰스 서머스", hei: "203cm", wei: "159kg", pot: "Potential", abil: "Leadership, Weapon Master" },
{ id: "hero_crystal01", char: "크리스탈", suit: "올뉴, 올디퍼런트", tier: "1", name: "크리스탈리아 아마퀠린", hei: "167cm", wei: "50kg", pot: "Potential", abil: "Energy Projection, Command" },
{ id: "hero_crystal01_S01", char: "크리스탈", suit: "로얄 슈트", tier: "1", name: "크리스탈리아 아마퀠린", hei: "167cm", wei: "50kg", pot: "Potential", abil: "Energy Projection, Command" },
{ id: "hero_crystal01_S02", char: "크리스탈", suit: "판타스틱 포", tier: "1", name: "크리스탈리아 아마퀠린", hei: "167cm", wei: "50kg", pot: "Potential", abil: "Energy Projection, Command" },
{ id: "hero_cyclops01", char: "사이클롭스", suit: "클래식", tier: "3", name: "스캇 서머스", hei: "190cm", wei: "88kg", pot: "Potential", abil: "Command, Energy Projection" },
{ id: "hero_cyclops01_S01", char: "사이클롭스", suit: "에이지 오브 아포칼립스", tier: "3", name: "스캇 서머스", hei: "190cm", wei: "88kg", pot: "Potential", abil: "Command, Energy Projection" },
{ id: "hero_cyclops01_S02", char: "사이클롭스", suit: "마블 나우!", tier: "3", name: "스캇 서머스", hei: "190cm", wei: "88kg", pot: "Potential", abil: "Command, Energy Projection" },
{ id: "hero_cyclops01_S03", char: "사이클롭스", suit: "피닉스 파이브", tier: "3", name: "스캇 서머스", hei: "190cm", wei: "88kg", pot: "Potential", abil: "Command, Energy Projection, 피닉스 Force" },
{ id: "hero_daisyjohnson01", char: "데이지 존슨", suit: "드라마 - 에이전트 오브 쉴.드.", tier: "1", name: "데이지 루이즈 존슨", hei: "175cm", wei: "61kg", pot: "-", abil: "Agent, Mind Resist" },
{ id: "hero_daisyjohnson01_S01", char: "데이지 존슨", suit: "모던", tier: "1", name: "데이지 루이즈 존슨", hei: "175cm", wei: "61kg", pot: "-", abil: "Agent, Command" },
{ id: "hero_daisyjohnson01_S02", char: "데이지 존슨", suit: "드라마 - 에이전트 오브 쉴.드. (퀘이크)", tier: "1", name: "데이지 루이즈 존슨", hei: "175cm", wei: "61kg", pot: "-", abil: "Agent, Mind Resist" },
{ id: "hero_dazzler01", char: "대즐러", suit: "모던", tier: "1", name: "앨리슨 \"앨리\" 블레어", hei: "177cm", wei: "52kg", pot: "Potential", abil: "Energy Projection" },
{ id: "hero_doctorstrange01", char: "닥터 스트레인지", suit: "올뉴, 올디퍼런트", tier: "3", name: "스티븐 빈센트 스트레인지", hei: "188cm", wei: "82kg", pot: "Potential", abil: "Magic, Fast Movement" },
{ id: "hero_doctorstrange01_S01", char: "닥터 스트레인지", suit: "영화 - 닥터 스트레인지", tier: "3", name: "스티븐 빈센트 스트레인지", hei: "188cm", wei: "82kg", pot: "Potential", abil: "Magic, Fast Movement" },
{ id: "hero_doctorstrange01_S02", char: "닥터 스트레인지", suit: "영화 - 어벤져스: 인피니티 워", tier: "3", name: "스티븐 빈센트 스트레인지", hei: "188cm", wei: "82kg", pot: "Potential", abil: "Magic, Fast Movement" },
{ id: "hero_doctorstrange01_S03", char: "닥터 스트레인지", suit: "Space 슈트", tier: "3", name: "스티븐 빈센트 스트레인지", hei: "188cm", wei: "82kg", pot: "Potential", abil: "Magic, Fast Movement" },
{ id: "hero_emmafrost01", char: "엠마 프로스트", suit: "모던", tier: "1", name: "엠마 그레이스 프로스트", hei: "178cm", wei: "65kg", pot: "Potential", abil: "Durability, Mind Resist" },
{ id: "hero_emmafrost01_S01", char: "엠마 프로스트", suit: "마블 나우!", tier: "1", name: "엠마 그레이스 프로스트", hei: "178cm", wei: "65kg", pot: "Potential", abil: "Durability, Mind Resist" },
{ id: "hero_emmafrost01_S02", char: "엠마 프로스트", suit: "피닉스 파이브", tier: "1", name: "엠마 그레이스 프로스트", hei: "178cm", wei: "65kg", pot: "Potential", abil: "Durability, Mind Resist, 피닉스 Force" },
{ id: "hero_gambit01", char: "갬빗", suit: "모던", tier: "1", name: "레미 에티엔 르보", hei: "186cm", wei: "81kg", pot: "Potential", abil: "Mind, Agility" },
{ id: "hero_humantorch01", char: "휴먼 토치", suit: "모던", tier: "1", name: "조나단 \"쟈니\" 로웰 스펜서 스톰", hei: "177cm", wei: "79kg", pot: "Potential", abil: "Flame, Fast Movement" },
{ id: "hero_humantorch01_S01", char: "휴먼 토치", suit: "퓨처 파운데이션", tier: "1", name: "조나단 \"쟈니\" 로웰 스펜서 스톰", hei: "179cm", wei: "77kg", pot: "Potential", abil: "Flame, Fast Movement" },
{ id: "hero_iceman01", char: "아이스맨", suit: "모던", tier: "1", name: "로버트 \"바비\" 루이스 드레이크", hei: "173cm", wei: "66kg", pot: "Potential", abil: "Chill, Cold Blooded" },
{ id: "hero_iceman01_S01", char: "아이스맨", suit: "엑스맨 블루", tier: "1", name: "로버트 \"바비\" 루이스 드레이크", hei: "173cm", wei: "66kg", pot: "Potential", abil: "Chill, Cold Blooded" },
{ id: "hero_inferno01", char: "인페르노", suit: "올뉴, 올디퍼런트", tier: "1", name: "단테 페르투스", hei: "180cm", wei: "73kg", pot: "Potential", abil: "Flame" },
{ id: "hero_inferno01_S01", char: "인페르노", suit: "모던", tier: "1", name: "단테 페르투스", hei: "180cm", wei: "73kg", pot: "Potential", abil: "Flame" },
{ id: "hero_invisiblewoman01", char: "인비저블 우먼", suit: "모던", tier: "1", name: "수잔 \"수\" 스톰", hei: "167cm", wei: "59kg", pot: "Potential", abil: "Energy Projection" },
{ id: "hero_invisiblewoman01_S01", char: "인비저블 우먼", suit: "퓨처 파운데이션", tier: "1", name: "수잔 \"수\" 스톰", hei: "167cm", wei: "59kg", pot: "Potential", abil: "Energy Projection" },
{ id: "hero_ironheart01", char: "아이언하트", suit: "마블 나우!", tier: "1", name: "리리 윌리엄스", hei: "162cm", wei: "52kg", pot: "-", abil: "Machine, Leadership" },
{ id: "hero_ironman01", char: "아이언 맨", suit: "영화 - 어벤져스", tier: "3", name: "앤서니 \"토니\" 에드워드 스타크", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 105kg, 착용후 193kg", pot: "Potential", abil: "Machine, Energy Projection" },
{ id: "hero_ironman01_S01", char: "아이언 맨", suit: "영화 - 어벤져스: 에이지 오브 울트론", tier: "3", name: "앤서니 \"토니\" 에드워드 스타크", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 105kg, 착용후 193kg", pot: "Potential", abil: "Machine, Energy Projection" },
{ id: "hero_ironman01_S02", char: "아이언 맨", suit: "시크릿 워즈: 2099", tier: "3", name: "앤서니 \"토니\" 에드워드 스타크", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 105kg, 착용후 193kg", pot: "Potential", abil: "Machine, Energy Projection" },
{ id: "hero_ironman01_S03", char: "아이언 맨", suit: "영화 - 캡틴 아메리카: 시빌 워", tier: "3", name: "앤서니 \"토니\" 에드워드 스타크", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 105kg, 착용후 193kg", pot: "Potential", abil: "Machine, Energy Projection" },
{ id: "hero_ironman01_S04", char: "아이언 맨", suit: "영화 - 어벤져스: 인피니티 워", tier: "3", name: "앤서니 \"토니\" 에드워드 스타크", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 105kg, 착용후 193kg", pot: "Potential", abil: "Machine, Energy Projection" },
{ id: "hero_ironman01_S05", char: "아이언 맨", suit: "영화 - 어벤져스: 엔드게임", tier: "3", name: "앤서니 \"토니\" 에드워드 스타크", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 105kg, 착용후 193kg", pot: "Potential", abil: "Machine, Energy Projection" },
{ id: "hero_ironman01_S06", char: "아이언 맨", suit: "영화 - 어벤져스: 엔드게임 (팀 슈트)", tier: "3", name: "앤서니 \"토니\" 에드워드 스타크", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 105kg, 착용후 193kg", pot: "Potential", abil: "Machine, Energy Projection" },
{ id: "hero_ironman01_S07", char: "아이언 맨", suit: "어벤져스 3099", tier: "3", name: "앤서니 \"토니\" 에드워드 스타크", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 105kg, 착용후 193kg", pot: "Potential", abil: "Machine, Energy Projection" },
{ id: "hero_jeangrey01", char: "진 그레이", suit: "피닉스", tier: "3", name: "진 일레인 그레이", hei: "167cm", wei: "52kg", pot: "Potential", abil: "피닉스 Force, Mind Resist, Mind" },
{ id: "hero_jeangrey01_S01", char: "진 그레이", suit: "엑스맨 레드", tier: "3", name: "진 일레인 그레이", hei: "167cm", wei: "52kg", pot: "Potential", abil: "피닉스 Force, Mind Resist, Mind" },
{ id: "hero_jeangrey01_S02", char: "진 그레이", suit: "마블 걸", tier: "3", name: "진 일레인 그레이", hei: "167cm", wei: "52kg", pot: "Potential", abil: "피닉스 Force, Mind Resist, Mind" },
{ id: "hero_jubilee01", char: "주빌리", suit: "클래식", tier: "1", name: "주빌레이션 리", hei: "165cm", wei: "52kg", pot: "Potential", abil: "Energy Projection" },
{ id: "hero_kidomega01", char: "키드 오메가", suit: "모던", tier: "1", name: "퀸타비우스 퀴리니우스 \"퀜틴\" 콰이어", hei: "cm", wei: "kg", pot: "Potential", abil: "피닉스 ForceEnergy Projection-" },
{ id: "hero_lincoln01", char: "링컨 캠벨", suit: "영화 - 에이전트 오브 쉴.드.", tier: "1", name: "링컨 캠벨", hei: "185cm", wei: "80kg", pot: "-", abil: "Shock" },
{ id: "hero_magik01", char: "매직", suit: "모던", tier: "1", name: "일리아나 니콜라예브나 라스푸티나", hei: "165cm", wei: "59kg", pot: "Potential", abil: "Mind Resist, Magic" },
{ id: "hero_magik01_S01", char: "매직", suit: "피닉스 파이브", tier: "1", name: "일리아나 니콜라예브나 라스푸티나", hei: "165cm", wei: "59kg", pot: "Potential", abil: "Mind Resist, Magic, 피닉스 Force" },
{ id: "hero_mantis01", char: "맨티스", suit: "영화 - 가디언즈 오브 갤럭시 Vol. 2", tier: "1", name: "브랜트", hei: "167cm", wei: "52kg", pot: "-", abil: "Mind, Healing" },
{ id: "hero_moongirl01", char: "문 걸", suit: "마블 나우!", tier: "1", name: "루넬라 루이즈 라파예트", hei: "121cm", wei: "34kg", pot: "Potential", abil: "Weapon Master, Leadership" },
{ id: "hero_moongirl01_S01", char: "문 걸", suit: "몬스터 언리쉬드!", tier: "1", name: "루넬라 루이즈 라파예트", hei: "121cm", wei: "34kg", pot: "Potential", abil: "Weapon Master, Leadership" },
{ id: "hero_nadiapym01", char: "와스프 (나디아 반 다인)", suit: "모던", tier: "1", name: "니다아 반 다인", hei: "162cm", wei: "54kg", pot: "-", abil: "Agent, Fast Movement" },
{ id: "hero_negasonic01", char: "네가소닉 틴에이지 워헤드", suit: "모던", tier: "1", name: "엘리 피미스터", hei: "162cm", wei: "52kg", pot: "Potential", abil: "Agility, Fast Movement, Energy Projection" },
{ id: "hero_nicominoru01", char: "시스터 그림", suit: "시크릿 워즈: 에이포스", tier: "1", name: "니코 마루", hei: "162cm", wei: "46kg", pot: "-", abil: "Magic" },
{ id: "hero_nicominoru01_S01", char: "시스터 그림", suit: "올뉴, 올디퍼런트", tier: "1", name: "니코 마루", hei: "162cm", wei: "46kg", pot: "-", abil: "Magic" },
{ id: "hero_philcoulson01", char: "필 콜슨", suit: "드라마 - 에이전트 오브 쉴.드.", tier: "1", name: "필립 \"필\" J. 콜슨", hei: "183cm", wei: "92kg", pot: "Potential", abil: "Agent, Command" },
{ id: "hero_philcoulson01_S01", char: "필 콜슨", suit: "드라마 - 에이전트 오브 쉴.드. 시즌 3", tier: "1", name: "필립 \"필\" J. 콜슨", hei: "183cm", wei: "92kg", pot: "Potential", abil: "Agent, Command" },
{ id: "hero_professorx01", char: "프로페서 엑스", suit: "모던", tier: "3", name: "찰스 프랜시스 자비에", hei: "183cm", wei: "86kg", pot: "Potential", abil: "Leadership, Mind Resist, Mind" },
{ id: "hero_psylocke01", char: "사일록", suit: "엑스포스", tier: "1", name: "엘리자베스 \"벳시\" 브래독", hei: "180cm", wei: "70kg", pot: "Potential", abil: "Mind, Agility" },
{ id: "hero_psylocke01_S01", char: "사일록", suit: "디스어셈블드", tier: "1", name: "엘리자베스 \"벳시\" 브래독", hei: "180cm", wei: "70kg", pot: "Potential", abil: "Mind, Agility" },
{ id: "hero_rachelsummers01", char: "레이첼 서머스", suit: "모던", tier: "1", name: "레이첼 \"레이\" 앤 서머스", hei: "170cm", wei: "57kg", pot: "Potential", abil: "Fast Movement, Phoenix Force" },
{ id: "hero_rescue01", char: "레스큐", suit: "영화 - 어벤져스: 엔드게임", tier: "1", name: "버지니아 \"페퍼\" 포츠", hei: "163cm", wei: "50kg", pot: "Potential", abil: "Machine, Leadership" },
{ id: "hero_rocketraccoon01", char: "로켓 라쿤", suit: "영화 - 가디언즈 오브 갤럭시", tier: "1", name: "로켓 라쿤", hei: "122cm", wei: "25kg", pot: "Potential", abil: "Weapon Master" },
{ id: "hero_rocketraccoon01_S01", char: "로켓 라쿤", suit: "올뉴, 올디퍼런트", tier: "1", name: "로켓 라쿤", hei: "122cm", wei: "25kg", pot: "Potential", abil: "Weapon Master" },
{ id: "hero_rocketraccoon01_S02", char: "로켓 라쿤", suit: "영화 - 가디언즈 오브 갤럭시 Vol. 2", tier: "1", name: "로켓 라쿤", hei: "122cm", wei: "25kg", pot: "Potential", abil: "Weapon Master" },
{ id: "hero_rocketraccoon01_S03", char: "로켓 라쿤", suit: "영화 - 어벤져스: 인피니티 워", tier: "1", name: "로켓 라쿤", hei: "122cm", wei: "25kg", pot: "Potential", abil: "Weapon Master" },
{ id: "hero_rocketraccoon01_S04", char: "로켓 라쿤", suit: "영화 - 어벤져스: 엔드게임", tier: "1", name: "로켓 라쿤", hei: "122cm", wei: "25kg", pot: "Potential", abil: "Weapon Master" },
{ id: "hero_rocketraccoon01_S05", char: "로켓 라쿤", suit: "영화 - 어벤져스: 엔드게임 (팀 슈트)", tier: "1", name: "로켓 라쿤", hei: "122cm", wei: "25kg", pot: "Potential", abil: "Weapon Master" },
{ id: "hero_scarletwitch01", char: "스칼렛 위치", suit: "클래식", tier: "3", name: "완다 막시모프", hei: "170cm", wei: "60kg", pot: "Potential", abil: "Chaos Magic, Fast Movement" },
{ id: "hero_scarletwitch01_S01", char: "스칼렛 위치", suit: "영화 - 어벤져스: 인피니티 워", tier: "3", name: "완다 막시모프", hei: "170cm", wei: "60kg", pot: "Potential", abil: "Chaos Magic, Fast Movement" },
{ id: "hero_scarletwitch01_S02", char: "스칼렛 위치", suit: "언캐니 어벤져스", tier: "3", name: "완다 막시모프", hei: "170cm", wei: "60kg", pot: "Potential", abil: "Chaos Magic, Fast Movement" },
{ id: "hero_scarletwitch01_S03", char: "스칼렛 위치", suit: "올뉴, 올디퍼런트", tier: "3", name: "완다 막시모프", hei: "170cm", wei: "60kg", pot: "Potential", abil: "Chaos Magic, Fast Movement" },
{ id: "hero_sharonrogers01", char: "캡틴 아메리카 (샤론 로저스)", suit: "캡틴 아메리카 75주년 기념", tier: "3", name: "샤론 로저스", hei: "173cm", wei: "61kg", pot: "Potential", abil: "Leadership, Energy Projection" },
{ id: "hero_sharonrogers01_S01", char: "캡틴 아메리카 (샤론 로저스)", suit: "스타라이트 아머", tier: "3", name: "샤론 로저스", hei: "173cm", wei: "61kg", pot: "Potential", abil: "Leadership, Energy Projection" },
{ id: "hero_sharonrogers01_S02", char: "캡틴 아메리카 (샤론 로저스)", suit: "다크 스타 아머", tier: "3", name: "샤론 로저스", hei: "173cm", wei: "61kg", pot: "Potential", abil: "Leadership, Energy Projection" },
{ id: "hero_sharonrogers01_S03", char: "캡틴 아메리카 (샤론 로저스)", suit: "스타 나이트 아머 ", tier: "3", name: "샤론 로저스", hei: "173cm", wei: "61kg", pot: "Potential", abil: "Leadership, Energy Projection" },
{ id: "hero_songbird01", char: "송버드", suit: "뉴 어벤져스", tier: "1", name: "멜리사 조안 골드", hei: "165cm", wei: "66kg", pot: "Potential", abil: "Agent, Fast Movement" },
{ id: "hero_starlord01", char: "스타로드", suit: "영화 - 가디언즈 오브 갤럭시", tier: "3", name: "피터 제이슨 퀼", hei: "188cm", wei: "79kg", pot: "Potential", abil: "Command, Weapon Master" },
{ id: "hero_starlord01_S01", char: "스타로드", suit: "스페이스 아머", tier: "3", name: "피터 제이슨 퀼", hei: "188cm", wei: "79kg", pot: "Potential", abil: "Command, Weapon Master" },
{ id: "hero_starlord01_S02", char: "스타로드", suit: "영화 - 가디언즈 오브 갤럭시 Vol. 2", tier: "3", name: "피터 제이슨 퀼", hei: "188cm", wei: "79kg", pot: "Potential", abil: "Command, Weapon Master" },
{ id: "hero_starlord01_S03", char: "스타로드", suit: "영화 - 어벤져스: 인피니티 워", tier: "3", name: "피터 제이슨 퀼", hei: "188cm", wei: "79kg", pot: "Potential", abil: "Command, Weapon Master" },
{ id: "hero_starlord01_S04", char: "스타로드", suit: "그라운디드", tier: "3", name: "피터 제이슨 퀼", hei: "188cm", wei: "79kg", pot: "Potential", abil: "Command, Weapon Master" },
{ id: "hero_storm01", char: "스톰", suit: "모던", tier: "1", name: "오로로 먼로", hei: "180cm", wei: "66kg", pot: "Potential", abil: "Command, Shock" },
{ id: "hero_storm01_S01", char: "스톰", suit: "엑스맨 레드", tier: "1", name: "오로로 먼로", hei: "180cm", wei: "66kg", pot: "Potential", abil: "Command, Shock" },
{ id: "hero_storm01_S02", char: "스톰", suit: "인휴먼즈 대 엑스맨", tier: "1", name: "오로로 먼로", hei: "180cm", wei: "66kg", pot: "Potential", abil: "Command, Shock" },
{ id: "hero_vision01", char: "비젼", suit: "모던", tier: "1", name: "비젼", hei: "190cm", wei: "136kg", pot: "Potential", abil: "Machin, Fast Movemente, Durability" },
{ id: "hero_vision01_S01", char: "비젼", suit: "영화 - 어벤져스: 에이지 오브 울트론", tier: "1", name: "비젼", hei: "190cm", wei: "136kg", pot: "Potential", abil: "Machin, Fast Movemente, Durability" },
{ id: "hero_vision01_S02", char: "비젼", suit: "언캐니 어벤져스", tier: "1", name: "비젼", hei: "190cm", wei: "136kg", pot: "Potential", abil: "Machin, Fast Movemente, Durability" },
{ id: "hero_warmachine01", char: "워 머신", suit: "모던", tier: "1", name: "제임스 \"짐\" 루퍼트 \"로디\" 로즈", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 109kg, 착용후 213kg", pot: "Potential", abil: "Leadership, Machine" },
{ id: "hero_warmachine01_S01", char: "워 머신", suit: "아이언 패트리어트", tier: "1", name: "제임스 \"짐\" 루퍼트 \"로디\" 로즈", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 109kg, 착용후 213kg", pot: "Potential", abil: "Leadership, Machine" },
{ id: "hero_warmachine01_S02", char: "워 머신", suit: "어벤져스: 이니셔티브", tier: "1", name: "제임스 \"짐\" 루퍼트 \"로디\" 로즈", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 109kg, 착용후 213kg", pot: "Potential", abil: "LeadershipMachine, " },
{ id: "hero_warmachine01_S03", char: "워 머신", suit: "영화 - 캡틴 아메리카: 시빌 워", tier: "1", name: "제임스 \"짐\" 루퍼트 \"로디\" 로즈", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 109kg, 착용후 213kgg", pot: "Potential", abil: "Leadership, Machine" },
{ id: "hero_warmachine01_S04", char: "워 머신", suit: "영화 - 어벤져스: 인피니티 워", tier: "1", name: "제임스 \"짐\" 루퍼트 \"로디\" 로즈", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 109kg, 착용후 213kg", pot: "Potential", abil: "Leadership, Machine" },
{ id: "hero_warmachine01_S05", char: "워 머신", suit: "영화 - 어벤져스: 엔드게임", tier: "1", name: "제임스 \"짐\" 루퍼트 \"로디\" 로즈", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 109kg, 착용후 213kg", pot: "Potential", abil: "Leadership, Machine" },
{ id: "hero_warmachine01_S06", char: "워 머신", suit: "영화 - 어벤져스: 엔드게임 (팀 슈트)", tier: "1", name: "제임스 \"짐\" 루퍼트 \"로디\" 로즈", hei: "착용전 185cm, 착용후 198cm", wei: "착용전 109kg, 착용후 213kg", pot: "Potential", abil: "Leadership, Machine" },
{ id: "hero_wasp01", char: "와스프", suit: "모던", tier: "1", name: "자넷 반 다인", hei: "163cm", wei: "50kg", pot: "Potential", abil: "Fast Movement" },
{ id: "hero_wasp01_S01", char: "와스프", suit: "올뉴, 올디퍼런트", tier: "1", name: "자넷 반 다인", hei: "163cm", wei: "50kg", pot: "Potential", abil: "Fast Movement" },
{ id: "hero_wasp01_S02", char: "와스프", suit: "영화 - 앤트맨과 와스프", tier: "1", name: "자넷 반 다인", hei: "163cm", wei: "50kg", pot: "Potential", abil: "Fast Movement" },
{ id: "hero_weaponhex01", char: "웨폰 헥스", suit: "인피니피 워프", tier: "1", name: "로라 키니", hei: "170cm", wei: "60kg", pot: "Potential", abil: "Chaos Magic, Healing, Agility" },
{ id: "hero_wiccan01", char: "위컨", suit: "뉴 어벤져스", tier: "1", name: "윌리엄 \"빌리\" 캐플런", hei: "173cm", wei: "70kg", pot: "Potential", abil: "Energy Projection, Fast Movement" },

// 블라스트 악당
{ id: "sv_baronmordo01", char: "모르도 남작", suit: "클래식", tier: "1", name: "칼 아마데우스 모르도", hei: "183cm", wei: "113kg", pot: "-", abil: "Magic, Pure Evil" },
{ id: "sv_baronmordo01_S01", char: "모르도 남작", suit: "영화 - 닥터 스트레인지", tier: "1", name: "칼 아마데우스 모르도", hei: "183cm", wei: "113kg", pot: "-", abil: "Magic, Pure Evil" },
{ id: "sv_enchantress01", char: "인챈트리스", suit: "모던", tier: "1", name: "아모라", hei: "190cm", wei: "204kg", pot: "Potential", abil: "Magic, Mind" },
{ id: "sv_enchantress01_S01", char: "인챈트리스", suit: "섬머 데이즈", tier: "1", name: "아모라", hei: "190cm", wei: "204kg", pot: "Potential", abil: "Magic, Mind" },
{ id: "sv_hydroman01", char: "하이드로맨", suit: "영화 - 스파이더맨: 파 프롬 홈", tier: "1", name: "모리스 벤치", hei: "188cm", wei: "120kg", pot: "Potential", abil: "Pure Evil" },
{ id: "sv_kaecilius01", char: "케실리우스", suit: "영화 - 닥터 스트레인지", tier: "1", name: "케실리우스", hei: "183cm", wei: "75kg", pot: "-", abil: "Magic, Agility" },
{ id: "sv_lash01", char: "래쉬", suit: "영화 - 에이전트 오브 쉴.드.", tier: "1", name: "불명", hei: "불명", wei: "불명", pot: "-", abil: "Energy Projection" },
{ id: "sv_lash01_S01", char: "래쉬", suit: "모던", tier: "1", name: "불명", hei: "불명", wei: "불명", pot: "-", abil: "Energy Projection" },
{ id: "sv_magneto01", char: "매그니토", suit: "클래식", tier: "3", name: "막스 아이젠하르트 / 에릭 마그누스 렌셔", hei: "188cm", wei: "86kg", pot: "Potential", abil: "Energy Projection, Mind Resist" },
{ id: "sv_magneto01_S01", char: "매그니토", suit: "마블 나우!", tier: "3", name: "막스 아이젠하르트 / 에릭 마그누스 렌셔", hei: "188cm", wei: "86kg", pot: "Potential", abil: "Energy Projection, Mind Resist" },
{ id: "sv_magneto01_S02", char: "매그니토", suit: "하우스 오브 엑스", tier: "3", name: "막스 아이젠하르트 / 에릭 마그누스 렌셔", hei: "188cm", wei: "86kg", pot: "Potential", abil: "Energy Projection, Mind Resist" },
{ id: "sv_malekith01", char: "말레키스", suit: "영화 - 토르: 다크 월드", tier: "1", name: "말레키스", hei: "206cm", wei: "84kg", pot: "-", abil: "Pure Evil" },
{ id: "sv_malekith01_S01", char: "말레키스", suit: "올뉴, 올디퍼런트", tier: "1", name: "말레키스", hei: "206cm", wei: "84kg", pot: "-", abil: "Pure Evil" },
{ id: "sv_maximus01", char: "막시무스 더 매드", suit: "워 오브 킹즈", tier: "1", name: "막시무스 볼타곤", hei: "180cm", wei: "82kg", pot: "Potential", abil: "Mind Resist, Pure Evil" },
{ id: "sv_modok01", char: "M.O.D.O.K.", suit: "클래식", tier: "1", name: "조지 탈튼", hei: "366cm", wei: "340kg", pot: "-", abil: "Machine, Pure Evil, Mind" },
{ id: "sv_modok01_S01", char: "M.O.D.O.K.", suit: "스파이독", tier: "1", name: "조지 탈튼", hei: "366cm", wei: "340kg", pot: "-", abil: "Machine, Pure Evil, Mind" },
{ id: "sv_modok01_S02", char: "M.O.D.O.K.", suit: "캡톡", tier: "1", name: "조지 탈튼", hei: "366cm", wei: "340kg", pot: "-", abil: "Machine, Pure Evil, Mind" },
{ id: "sv_mistersinister01", char: "미스터 시니스터", suit: "모던", tier: "1", name: "나다니엘 에식스", hei: "196cm", wei: "120kg", pot: "Potential", abil: "Pure Evil, Energy Projection, Healing" },
{ id: "sv_mysterio01", char: "미스테리오", suit: "클래식", tier: "1", name: "퀜틴 벡", hei: "180cm", wei: "79kg", pot: "Potential", abil: "Mind, Sinister Six" },
{ id: "sv_mysterio01_S01", char: "미스테리오", suit: "영화 - 스파이더맨: 파 프롬 홈", tier: "1", name: "퀜틴 벡", hei: "180cm", wei: "79kg", pot: "Potential", abil: "Mind, Sinister Six" },
{ id: "sv_redskull01", char: "레드 스컬", suit: "캡틴 아메리카: 퍼스트 어벤져", tier: "1", name: "조나단 슈미트", hei: "185cm", wei: "88kg", pot: "Potential", abil: "Command, Pure Evil" },
{ id: "sv_redskull01_S01", char: "레드 스컬", suit: "시크릿 워즈: 레드 스컬", tier: "1", name: "조나단 슈미트", hei: "185cm", wei: "88kg", pot: "Potential", abil: "Command, Pure Evil" },
{ id: "sv_redskull01_S02", char: "레드 스컬", suit: "하이드라 아머", tier: "1", name: "조나단 슈미트", hei: "185cm", wei: "88kg", pot: "Potential", abil: "Command, Pure Evil, Cosmic Cube" },
{ id: "sv_stryfe01", char: "스트라이프", suit: "모던", tier: "1", name: "케이블 복제인가", hei: "203cm", wei: "159kg", pot: "Potential", abil: "Pure Evil, Energy Projection" },
{ id: "sv_ulyssesklaue01", char: "율리시스 클로", suit: "영화 - 블랙 팬서", tier: "1", name: "율리시스 S. 클로", hei: "180cm", wei: "79kg", pot: "-", abil: "Weapon Master" },
{ id: "sv_whiplash01", char: "위플래쉬", suit: "영화 - 아이언 맨 2", tier: "1", name: "안톤 반코", hei: "183cm", wei: "70kg", pot: "-", abil: "Machine, Shock" },
{ id: "sv_yellowjacket01", char: "옐로우재킷", suit: "영화 - 앤트맨", tier: "1", name: "대런 아고니스테스 크로스", hei: "183cm", wei: "83kg", pot: "-", abil: "Machine, Pure Evil" },
{ id: "sv_yellowjacket01_S01", char: "옐로우재킷", suit: "마블 나우!", tier: "1", name: "대런 아고니스테스 크로스", hei: "183cm", wei: "83kg", pot: "-", abil: "Machine, Pure Evil" },

// 유니버셜 영웅
{ id: "hero_angela01", char: "안젤라", suit: "모던", tier: "1", name: "알드리프", hei: "188cm", wei: "218kg", pot: "-", abil: "Weapon Master" },
{ id: "hero_angela01_S01", char: "안젤라", suit: "시크릿 워즈: 1602 (위치 헌터 안젤라)", tier: "1", name: "알드리프", hei: "188cm", wei: "218kg", pot: "-", abil: "Weapon Master" },
{ id: "hero_angela01_S02", char: "안젤라", suit: "올뉴, 올디퍼런트", tier: "1", name: "알드리프", hei: "188cm", wei: "218kg", pot: "-", abil: "Weapon Master" },
{ id: "hero_betaraybill01", char: "베타 레이 빌", suit: "모던", tier: "2", name: "베타 레이 빌", hei: "201cm", wei: "217kg", pot: "Potential", abil: "Leadership, Shock" },
{ id: "hero_blackbolt01", char: "블랙 볼트", suit: "모던", tier: "3", name: "블랙카가르 볼타곤", hei: "188cm", wei: "95kg", pot: "Potential", abil: "Energy Projection, Fast Movement" },
{ id: "hero_blackbolt01_S01", char: "블랙 볼트", suit: "올뉴, 올디퍼런트", tier: "3", name: "블랙카가르 볼타곤", hei: "188cm", wei: "95kg", pot: "Potential", abil: "Energy Projection, Fast Movement" },
{ id: "hero_blackbolt01_S02", char: "블랙 볼트", suit: "인휴먼즈: 아틸란 라이징", tier: "3", name: "블랙카가르 볼타곤", hei: "188cm", wei: "95kg", pot: "Potential", abil: "Energy Projection, Fast Movement" },
{ id: "hero_blackbolt01_S03", char: "블랙 볼트", suit: "마블 엑스", tier: "3", name: "블랙카가르 볼타곤", hei: "188cm", wei: "95kg", pot: "Potential", abil: "Energy Projection, Fast Movement" },
{ id: "hero_bluemarvel01", char: "블루 마블", suit: "얼티미츠", tier: "1", name: "아담 버나드 브래스히어", hei: "193cm", wei: "104kg", pot: "-", abil: "Energy Projection, Leadership" },
{ id: "hero_captainmarvel01", char: "캡틴 마블", suit: "모던", tier: "3", name: "캐롤 수잔 제인 댄버스", hei: "180cm", wei: "75kg", pot: "Potential", abil: "Energy Projection, Fast Movement, Leadership" },
{ id: "hero_captainmarvel01_S01", char: "캡틴 마블", suit: "시크릿 워즈: 캡틴 마블과 캐럴 코어", tier: "3", name: "캐롤 수잔 제인 댄버스", hei: "180cm", wei: "75kg", pot: "Potential", abil: "Energy Projection, Fast Movement, Leadership" },
{ id: "hero_captainmarvel01_S02", char: "캡틴 마블", suit: "미즈 마블", tier: "3", name: "캐롤 수잔 제인 댄버스", hei: "180cm", wei: "75kg", pot: "Potential", abil: "Energy Projection, Fast Movement, Leadership" },
{ id: "hero_captainmarvel01_S03", char: "캡틴 마블", suit: "영화 - 캡틴 마블", tier: "3", name: "캐롤 수잔 제인 댄버스", hei: "180cm", wei: "75kg", pot: "Potential", abil: "Energy Projection, Fast Movement, Leadership" },
{ id: "hero_captainmarvel01_S04", char: "캡틴 마블", suit: "영화 - 어벤져스: 엔드게임", tier: "3", name: "캐롤 수잔 제인 댄버스", hei: "180cm", wei: "75kg", pot: "Potential", abil: "Energy Projection, Fast Movement, Leadership" },
{ id: "hero_clea01", char: "클레아", suit: "모던", tier: "1", name: "클레아", hei: "173cm", wei: "86kg", pot: "-", abil: "Magic, Fast Movement" },
{ id: "hero_doctorvoodoo01", char: "닥터 부두", suit: "모던", tier: "1", name: "제리코 드럼", hei: "183cm", wei: "100kg", pot: "Potential", abil: "Magic, Command" },
{ id: "hero_ghostpanther01", char: "고스트 팬서", suit: "인피니피 워프", tier: "1", name: "티찰라", hei: "193cm", wei: "91kg", pot: "Potential", abil: "Flame, Agility" },
{ id: "hero_ghostrider01", char: "고스트 라이더", suit: "클래식", tier: "1", name: "조나단 \"쟈니\" 블레이즈", hei: "변신전 178cm 변신후 188cm", wei: "변신전 82kg, 변신후 100kg", pot: "Potential", abil: "Flame, Leadership" },
{ id: "hero_ghostrider01_S01", char: "고스트 라이더", suit: "70년대 클래식", tier: "1", name: "조나단 \"쟈니\" 블레이즈", hei: "변신전 178cm 변신후 188cm", wei: "변신전 82kg, 변신후 100kg", pot: "Potential", abil: "Flame, Leadership" },
{ id: "hero_ghostrider01_S02", char: "고스트 라이더", suit: "인휴먼즈: 아틸란 라이징", tier: "1", name: "조나단 \"쟈니\" 블레이즈", hei: "변신전 178cm 변신후 188cm", wei: "변신전 82kg, 변신후 100kg", pot: "Potential", abil: "Flame, Leadership" },
{ id: "hero_ghostrider01_S03", char: "고스트 라이더", suit: "킹 오브 헬", tier: "1", name: "조나단 \"쟈니\" 블레이즈", hei: "변신전 178cm 변신후 188cm", wei: "변신전 82kg, 변신후 100kg", pot: "Potential", abil: "Flame, Leadership" },
{ id: "hero_heimdall01", char: "헤임달", suit: "영화 - 토르: 라그나로크", tier: "1", name: "헤임달", hei: "218cm", wei: "238kg", pot: "-", abil: "Strong" },
{ id: "hero_hellstorm01", char: "헬스트롬", suit: "모던", tier: "1", name: "다이몬 헬스트롬", hei: "185cm", wei: "82kg", pot: "-", abil: "Magic, Flame" },
{ id: "hero_hyperion01", char: "하이페리온", suit: "올뉴, 올디퍼런트", tier: "1", name: "마커스 밀튼", hei: "193cm", wei: "209kg", pot: "Potential", abil: "Leadership, Energy Projection" },
{ id: "hero_hyperion01_S01", char: "하이페리온", suit: "클래식", tier: "1", name: "마커스 밀튼", hei: "193cm", wei: "209kg", pot: "Potential", abil: "Leadership, Energy Projection" },
{ id: "hero_ironhammer01", char: "아이언 해머", suit: "인피니피 워프", tier: "1", name: "스타크 오딘슨", hei: "198cm", wei: "290kg", pot: "Potential", abil: "Machine, Shock, Magic" },
{ id: "hero_janefoster01", char: "토르 (제인 포스터)", suit: "올뉴, 올디퍼런트", tier: "1", name: "제인 포스터", hei: "170cm", wei: "61kg", pot: "-", abil: "Fast Movement, Shock" },
{ id: "hero_medusa01", char: "메두사", suit: "올뉴, 올디퍼런트", tier: "1", name: "메두살리스 아마퀠린", hei: "180cm", wei: "59kg", pot: "Potential", abil: "Command" },
{ id: "hero_medusa01_S01", char: "메두사", suit: "몬스터 언리쉬드! (MFF 배리언트)", tier: "1", name: "메두살리스 아마퀠린", hei: "180cm", wei: "59kg", pot: "Potential", abil: "Command" },
{ id: "hero_medusa01_S02", char: "메두사", suit: "인휴먼즈 대 엑스맨", tier: "1", name: "메두살리스 아마퀠린", hei: "180cm", wei: "59kg", pot: "Potential", abil: "Command" },
{ id: "hero_nova01", char: "노바 (샘 알렉산더)", suit: "올뉴, 올디퍼런트", tier: "1", name: "사무엘 \"샘\" 알렉산더", hei: "167cm", wei: "63kg", pot: "-", abil: "Energy Projection, Fast Movement" },
{ id: "hero_odin01", char: "오딘", suit: "모던", tier: "3", name: "오딘", hei: "206cm", wei: "295kg", pot: "Potential", abil: "Energy Projection, Command" },
{ id: "hero_odin01_S01", char: "오딘", suit: "올 파더", tier: "3", name: "오딘", hei: "206cm", wei: "295kg", pot: "Potential", abil: "Energy Projection, Command" },
{ id: "hero_phylavell01", char: "파일라-벨", suit: "모던", tier: "1", name: "파일라-벨", hei: "175cm", wei: "46kg", pot: "Potential", abil: "Energy Projection, Leadership" },
{ id: "hero_quasar01", char: "퀘이사 (에이브릴 킨케이드)", suit: "올뉴, 올디퍼런트", tier: "1", name: "에이브릴 킨케이드", hei: "167cm", wei: "63kg", pot: "-", abil: "Energy Projection, Heightened Senses" },
{ id: "hero_richardrider01", char: "노바 (리처드 라이더)", suit: "모던", tier: "1", name: "리처드 \"리치\" 라이더", hei: "185cm", wei: "86kg", pot: "Potential", abil: "Energy Projection, Leadership" },
{ id: "hero_robbiereyes01", char: "고스트 라이더 (로비 레예스)", suit: "마블 나우!", tier: "1", name: "로베르토 \"로비\" 레예스", hei: "180cm", wei: "82kg", pot: "-", abil: "Flame, Fast Movement" },
{ id: "hero_satana01", char: "사타나", suit: "모던", tier: "1", name: "사타나 헬스트롬", hei: "170cm", wei: "54kg", pot: "-", abil: "Magic, Flame" },
{ id: "hero_satana01_S01", char: "사타나", suit: "마블 레거시", tier: "1", name: "사타나 헬스트롬", hei: "170cm", wei: "54kg", pot: "-", abil: "Magic, Flame" },
{ id: "hero_shadowshell01", char: "쉐도우 셸", suit: "모던", tier: "1", name: "불명", hei: "168cm", wei: "53kg", pot: "Potential", abil: "Poison, Agility" },
{ id: "hero_silversurfer01", char: "실버 서퍼", suit: "모던", tier: "3", name: "노린 라드", hei: "193cm", wei: "102kg", pot: "Potential", abil: "Power Cosmic" },
{ id: "hero_silversurfer01_S01", char: "실버 서퍼", suit: "블랙", tier: "3", name: "노린 라드", hei: "193cm", wei: "102kg", pot: "Potential", abil: "Power Cosmic" },
{ id: "hero_singularity01", char: "싱귤래리티", suit: "시크릿 워즈: 에이포스", tier: "1", name: "불명", hei: "불명", wei: "불명", pot: "-", abil: "Fast Movement, Energy Projection" },
{ id: "hero_slapstick01", char: "슬랩스틱", suit: "모던", tier: "1", name: "스티븐 하몬", hei: "170cm", wei: "66kg", pot: "Potential", abil: "Agility" },
{ id: "hero_thor01", char: "토르", suit: "영화 - 어벤져스", tier: "3", name: "토르", hei: "198cm", wei: "290kg", pot: "Potential", abil: "Shock, Leadership" },
{ id: "hero_thor01_S01", char: "토르", suit: "영화 - 어벤져스: 에이지 오브 울트론", tier: "3", name: "토르", hei: "198cm", wei: "290kg", pot: "Potential", abil: "Shock, Leadership" },
{ id: "hero_thor01_S02", char: "토르", suit: "Unworthy", tier: "3", name: "토르", hei: "198cm", wei: "290kg", pot: "Potential", abil: "Shock, Leadership" },
{ id: "hero_thor01_S03", char: "토르", suit: "영화 - 토르: 라그나로크", tier: "3", name: "토르", hei: "198cm", wei: "290kg", pot: "Potential", abil: "Shock, Leadership" },
{ id: "hero_thor01_S04", char: "토르", suit: "영화 - 어벤져스: 인피니티 워", tier: "3", name: "토르", hei: "198cm", wei: "290kg", pot: "Potential", abil: "Shock, Leadership" },
{ id: "hero_thor01_S05", char: "토르", suit: "영화 - 어벤져스: 엔드게임", tier: "3", name: "토르", hei: "198cm", wei: "290kg", pot: "Potential", abil: "Shock, Leadership" },
{ id: "hero_thor01_S06", char: "토르", suit: "영화 - 어벤져스: 엔드게임 (팀 슈트)", tier: "3", name: "토르", hei: "198cm", wei: "290kg", pot: "Potential", abil: "Shock, Leadership" },

// 유니버셜 악당
{ id: "sv_antiman01", char: "안티맨", suit: "올뉴, 올디퍼런트", tier: "1", name: "코너 심스", hei: "193cm", wei: "113kg", pot: "-", abil: "Energy Projection, Fast Movement" },
{ id: "sv_blackdwarf01", char: "블랙 드워프", suit: "인피니티", tier: "1", name: "컬 옵시디언", hei: "213cm", wei: "499kg", pot: "Potential", abil: "Strong, Durability" },
{ id: "sv_blackdwarf01_S01", char: "블랙 드워프", suit: "영화 - 어벤져스: 인피니티 워 (컬 옵시디언)", tier: "1", name: "컬 옵시디언", hei: "213cm", wei: "499kg", pot: "Potential", abil: "Strong, Durability" },
{ id: "sv_corvusglaive01", char: "콜버스 글레이브", suit: "인피니티", tier: "1", name: "콜버스 글레이브", hei: "178cm", wei: "79kg", pot: "Potential", abil: "Fast Movement, Agility" },
{ id: "sv_corvusglaive01_S01", char: "콜버스 글레이브", suit: "영화 - 어벤져스: 인피니티 워", tier: "1", name: "콜버스 글레이브", hei: "178cm", wei: "79kg", pot: "Potential", abil: "Fast Movement, Agility" },
{ id: "sv_destroyer01", char: "디스트로이어", suit: "클래식", tier: "1", name: "디스트로이어", hei: "290cm", wei: "366kg", pot: "-", abil: "Flame" },
{ id: "sv_destroyer01_S01", char: "디스트로이어", suit: "프로메티우스", tier: "1", name: "디스트로이어", hei: "290cm", wei: "366kg", pot: "-", abil: "Energy Projection" },
{ id: "sv_doctordoom01", char: "닥터 둠", suit: "모던", tier: "2", name: "빅터 본 둠", hei: "착용전 188cm, 착용후 201cm", wei: "착용전 91kg, 착용후 188kg", pot: "Potential", abil: "Magic, Pure Evil" },
{ id: "sv_dormmamu01", char: "도르마무", suit: "클래식", tier: "2", name: "도르마무", hei: "변동", wei: "변동", pot: "-", abil: "Magic" },
{ id: "sv_dormmamu01", char: "도르마무", suit: "댐네이션", tier: "2", name: "도르마무", hei: "변동", wei: "변동", pot: "-", abil: "Magic" },
{ id: "sv_ebonymaw01", char: "에보니 모", suit: "인피니티", tier: "1", name: "에보니 모", hei: "178cm", wei: "79kg", pot: "Potential", abil: "Fast Movement, Mind Resist, Mind" },
{ id: "sv_ebonymaw01_S01", char: "에보니 모", suit: "영화 - 어벤져스: 인피니티 워", tier: "1", name: "에보니 모", hei: "178cm", wei: "79kg", pot: "Potential", abil: "Fast Movement, Mind Resist, Mind" },
{ id: "sv_hela01", char: "헬라", suit: "모던", tier: "1", name: "헬라", hei: "198cm", wei: "227kg", pot: "-", abil: "Pure Evil, Command" },
{ id: "sv_hela01_S01", char: "헬라", suit: "영화 - 토르: 라그나로크", tier: "1", name: "헬라", hei: "198cm", wei: "227kg", pot: "-", abil: "Pure Evil, Command" },
{ id: "sv_loki01", char: "로키", suit: "영화 - 어벤져스", tier: "1", name: "로키", hei: "193cm", wei: "238kg", pot: "Potential", abil: "Chill, Mind" },
{ id: "sv_loki01_S01", char: "로키", suit: "레이디 로키", tier: "1", name: "로키", hei: "193cm", wei: "238kg", pot: "Potential", abil: "Chill, Mind" },
{ id: "sv_loki01_S02", char: "로키", suit: "영화 - 토르: 라그나로크", tier: "1", name: "로키", hei: "193cm", wei: "238kg", pot: "Potential", abil: "Chill, Mind" },
{ id: "sv_loki01_S03", char: "로키", suit: "클래식", tier: "1", name: "로키", hei: "193cm", wei: "238kg", pot: "Potential", abil: "Chill, Mind" },
{ id: "sv_morganlefay01", char: "모간 르 페이", suit: "모던", tier: "1", name: "모간 르 페이", hei: "188cm", wei: "64kg", pot: "Potential", abil: "Magic, Pure Evil" },
{ id: "sv_proximamidnight01", char: "프록시마 미드나이트", suit: "인피니티", tier: "2", name: "프록시마 미드나이트", hei: "198cm", wei: "217kg", pot: "Potential", abil: "Agility, Fast Movement" },
{ id: "sv_proximamidnight01_S01", char: "프록시마 미드나이트", suit: "영화 - 어벤져스: 인피니티 워", tier: "2", name: "프록시마 미드나이트", hei: "198cm", wei: "217kg", pot: "Potential", abil: "Agility, Fast Movement" },
{ id: "sv_ronan01", char: "로난 더 어큐저", suit: "영화 - 가디언즈 오브 갤럭시", tier: "1", name: "로난", hei: "226cm", wei: "218kg", pot: "Potential", abil: "Mind Resist, Command" },
{ id: "sv_ronan01_S01", char: "로난 더 어큐저", suit: "어나힐레이션", tier: "1", name: "로난", hei: "226cm", wei: "218kg", pot: "Potential", abil: "Mind Resist, Command" },
{ id: "sv_ronan01_S02", char: "로난 더 어큐저", suit: "영화 - 캡틴 마블", tier: "1", name: "로난", hei: "226cm", wei: "218kg", pot: "Potential", abil: "Mind Resist, Command" },
{ id: "sv_sentinel01", char: "센티넬", suit: "모던", tier: "1", name: "센티넬", hei: "230cm", wei: "400t", pot: "Potential", abil: "Machine, Pure Evil" },
{ id: "sv_sentinel01_S01", char: "센티넬", suit: "님로드 더 레서", tier: "1", name: "센티넬", hei: "230cm", wei: "400t", pot: "Potential", abil: "Machine, Pure Evil" },
{ id: "sv_supergiant01", char: "슈퍼자이언트", suit: "인피니티", tier: "2", name: "슈퍼자이언트", hei: "198cm", wei: "217kg", pot: "-", abil: "Mind Resist, Mind" },
{ id: "sv_thane01", char: "테인", suit: "모던", tier: "1", name: "테인", hei: "180cm", wei: "81kg", pot: "Potential", abil: "Strong, Durability, Pure Evil" },
{ id: "sv_thanos01", char: "타노스", suit: "인피니티", tier: "3", name: "타노스", hei: "201cm", wei: "447kg", pot: "Potential", abil: "Power Cosmic, Durability, Pure Evil" },
{ id: "sv_thanos01_S01", char: "타노스", suit: "시크릿 워즈: 인피니티", tier: "3", name: "타노스", hei: "201cm", wei: "447kg", pot: "Potential", abil: "Power Cosmic, Durability, Pure Evil" },
{ id: "sv_thanos01_S02", char: "타노스", suit: "영화 - 어벤져스: 인피니티 워", tier: "3", name: "타노스", hei: "201cm", wei: "447kg", pot: "Potential", abil: "Power Cosmic, Durability, Pure Evil" },
{ id: "sv_thanos01_S03", char: "타노스", suit: "영화 - 어벤져스: 엔드게임", tier: "3", name: "타노스", hei: "201cm", wei: "447kg", pot: "Potential", abil: "Power Cosmic, Durability, Pure Evil" },
{ id: "sv_ultron_boss01", char: "울트론", suit: "모던", tier: "1", name: "울트론", hei: "206cm", wei: "333kg", pot: "-", abil: "Machine, Pure Evil" },
{ id: "sv_ultron_boss01_S01", char: "울트론 프라임", suit: "영화 - 어벤져스: 에이지 오브 울트론", tier: "1", name: "울트론", hei: "206cm", wei: "333kg", pot: "-", abil: "Machine, Pure Evil" },
{ id: "sv_ultron_boss01_S02", char: "울트론 마크 1", suit: "영화 - 어벤져스: 에이지 오브 울트론", tier: "1", name: "울트론", hei: "206cm", wei: "333kg", pot: "-", abil: "Machine, Pure Evil" },
{ id: "sv_ultron_boss01_S03", char: "울트론 마크 3", suit: "영화 - 어벤져스: 에이지 오브 울트론", tier: "1", name: "울트론", hei: "206cm", wei: "333kg", pot: "-", abil: "Machine, Pure Evil" },
{ id: "sv_victorious01", char: "빅토리우스", suit: "모던", tier: "1", name: "조라 부코비치", hei: "183cm", wei: "77kg", pot: "Potential", abil: "Energy Projection, Fast Movement" },


// NPC
{ id: "boss_fenriswolf01", char: "Fenris Wolf", suit: "펜리르 울프", tier: "<>", name: "", hei: "cm", wei: "kg", pot: "<>", abil: "---" },
{ id: "boss_fenriswolf01_S01", char: "Fenris Wolf", suit: "펜리르 울프", tier: "<>", name: "", hei: "cm", wei: "kg", pot: "<>", abil: "---" },
{ id: "boss_frostbeast01", char: "Frost Beast", suit: "프로스트 비스트", tier: "<>", name: "", hei: "cm", wei: "kg", pot: "<>", abil: "---" },
{ id: "boss_frostbeast01_S01", char: "Frost Beast", suit: "Burn", tier: "<>", name: "", hei: "cm", wei: "kg", pot: "<>", abil: "---" },
{ id: "boss_frostbeast01_S02", char: "Frost Beast", suit: "Paralize", tier: "<>", name: "", hei: "cm", wei: "kg", pot: "<>", abil: "---" },
{ id: "boss_frostbeast01_S03", char: "Frost Beast", suit: "Silence", tier: "<>", name: "", hei: "cm", wei: "kg", pot: "<>", abil: "---" },
{ id: "boss_mbaku01", char: "음바쿠", suit: "영화 - 블랙 팬서", tier: "1", name: "음바쿠", hei: "213cm", wei: "161kg", pot: "-", abil: "---" },
{ id: "boss_mdigardserpent01", char: "Midgard Serpent", suit: "미드가르드 서펀트", tier: "<>", name: "", hei: "cm", wei: "kg", pot: "<>", abil: "---" },
{ id: "boss_surtur01", char: "Surtur", suit: "수르트", tier: "<>", name: "", hei: "cm", wei: "kg", pot: "<>", abil: "---" },
{ id: "boss_talos01", char: "탈로스", suit: "영화 - 캡틴 마블", tier: "1", name: "탈로스", hei: "cm", wei: "kg", pot: "<>", abil: "---" },
{ id: "boss_ymir01", char: "Ymir", suit: "이미르", tier: "<>", name: "", hei: "cm", wei: "kg", pot: "<>", abil: "---" },
{ id: "GM_Jocasta01", char: "Jocasta", suit: "조캐스타", tier: "1", name: "", hei: "175cm", wei: "340kg", pot: "-", abil: "---" },
{ id: "hero_melindamay01", char: "멜린다 메이", suit: "드라마 - 에이전트 오브 쉴.드.", tier: "1", name: "멜린다 차오롄 메이", hei: "163cm", wei: "50kg", pot: "-", abil: "---" },
{ id: "sv_devildinosaur01", char: "Devil Dinosaur", suit: "데빌 다이너소어", tier: "<>", name: "", hei: "cm", wei: "kg", pot: "<>", abil: "---" },
{ id: "hero_io01", char: "Io", suit: "이오", tier: "<>", name: "", hei: "cm", wei: "kg", pot: "<>", abil: "---" },


   ];

  event.preventDefault();
})
