$(document).ready(function(event){
 
  $( "[id^=btn]" ).css({"cursor": "pointer"}).click(function() {
  
    const name = $(this).attr("name");
    const type = $(this).attr("type");
    const sex = $(this).attr("sex");
    const side = $(this).attr("side");

    const print = [ ];
    const styleProps = $( this ).css([
      "width", "height", "color", "background-color", "background-image"
    ]);

    $( '[id^="btn"]' ).removeClass('selected');
    $( ".gra-port" ).css({"background-image": "url(./portraits/"+name+".png)"}).removeClass('selected');
    $( ".ico-type" ).css({"background-image": "url(./icons/"+type+".png)"}).removeClass('selected');
    $( ".ico-sex" ).css({"background-image": "url(./icons/"+sex+".png)"}).removeClass('selected');
    $( ".ico-side" ).css({"background-image": "url(./icons/"+side+".png)"}).removeClass('selected');

    $(this).addClass('selected');
    $( ".gra-port" ).css({"background-image": "url(./portraits/"+name+".png)"}).addClass('selected');
    $( ".ico-type" ).css({"background-image": "url(./icons/"+type+".png)"}).addClass('selected');
    $( ".ico-sex" ).css({"background-image": "url(./icons/"+sex+".png)"}).addClass('selected');
    $( ".ico-side" ).css({"background-image": "url(./icons/"+side+".png)"}).addClass('selected');

    const fchar = [], fsuit = [], ftier= [], fname= [], fhei = [], fwei = [], fpot = [], fabil = [];

    $.each(figure, function(idx, obj) {    
      if (name == obj.id) {

        fchar.push( obj.char);
        fsuit.push( obj.suit + " " );
        ftier.push( obj.tier + " " );
        fname.push( obj.name + " " );
        fhei.push( obj.hei + " " );
        fwei.push( obj.wei + " " );
        fpot.push( obj.pot + " " );
        fabil.push( obj.abil + " " );

      }
    }); 

    $(".gra-char").text( fchar );
    $(".info-part-suit").text( fsuit );
    $(".info-part-tier").text( ftier );
    $(".info-part-name").text( fname );
    $(".info-part-hei").text( fhei );
    $(".info-part-wei").text( fwei );
    $(".info-part-pot").text( fpot );
    $(".info-part-abil").text( fabil );

  });
 
    var figure = [

{ id: "	hero_adamwarlock01	 " , char: "	Adam Warlock	 " , suit: "	모던	 " , tier: "	#	", name: "	아담 워록	", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Time Freezing ImmunityMagic	" },
{ id: "	hero_aero01	 " , char: "	Aero	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Agents of AtlasLeadershipFast Movement	" },
{ id: "	hero_agentvenom01	 " , char: "	Agent Venom	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	SymbioteLeadershipAgent	" },
{ id: "	hero_agentvenom01_S01	 " , char: "	Agent Venom	 " , suit: "	에이전트 안티베놈	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	SymbioteLeadershipAgent	" },
{ id: "	hero_amadeuscho01	 " , char: "	Hulk (Amadeus Cho)	 " , suit: "	토탈리 어썸 헐크	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Gamma RadiationDurability-	" },
{ id: "	hero_amadeuscho01_S01	 " , char: "	Hulk (Amadeus Cho)	 " , suit: "	몬스터 언리쉬드! (MFF 배리언트)	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Gamma RadiationDurability-	" },
{ id: "	hero_amadeuscho01_S02	 " , char: "	Hulk (Amadeus Cho)	 " , suit: "	브론	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Gamma RadiationDurability-	" },
{ id: "	hero_americachavez01	 " , char: "	America Chavez	 " , suit: "	얼티미츠	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Fast MovementStrong-	" },
{ id: "	hero_ancientone01	 " , char: "	Ancient One	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipMagic-	" },
{ id: "	hero_ancientone01_S01	 " , char: "	Ancient One	 " , suit: "	Marvel's 닥터 스트레인지	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipMagic-	" },
{ id: "	hero_angel01	 " , char: "	Angel	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipFast Movement-	" },
{ id: "	hero_angel01_S01	 " , char: "	Archangel	 " , suit: "	엑스포스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipFast Movement-	" },
{ id: "	hero_angela01	 " , char: "	Angela	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon Master--	" },
{ id: "	hero_angela01_S01	 " , char: "	Angela	 " , suit: "	시크릿 워즈: 1602 (위치 헌터 안젤라)	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon Master--	" },
{ id: "	hero_angela01_S02	 " , char: "	Angela	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon Master--	" },
{ id: "	hero_antman01	 " , char: "	Ant-Man	 " , suit: "	모던	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Agility--	" },
{ id: "	hero_antman01_S01	 " , char: "	Ant-Man	 " , suit: "	Marvel's 앤트맨	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Agility--	" },
{ id: "	hero_antman01_S02	 " , char: "	Ant-Man	 " , suit: "	Marvel's 캡틴 아메리카: 시빌 워	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Agility--	" },
{ id: "	hero_antman01_S03	 " , char: "	Ant-Man	 " , suit: "	Marvel's 앤트맨과 와스프	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Agility--	" },
{ id: "	hero_antman01_S04	 " , char: "	Ant-Man	 " , suit: "	Marvel's 어벤져스: 엔드게임	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AvengersAgility-	" },
{ id: "	hero_antman01_S05	 " , char: "	Ant-Man	 " , suit: "	Marvel's 어벤져스: 엔드게임 (팀 슈트)	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AvengersAgility-	" },
{ id: "	hero_arachknight01	 " , char: "	Arachknight	 " , suit: "	인피니피 워프	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipWeapon MasterSpider-Sense	" },
{ id: "	hero_beast01	 " , char: "	Beast	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityStrong-	" },
{ id: "	hero_beast01_S01	 " , char: "	Beast	 " , suit: "	에이지 오브 아포칼립스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityStrong-	" },
{ id: "	hero_beast01_S02	 " , char: "	Beast	 " , suit: "	언캐니 엑스맨	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityStrong-	" },
{ id: "	hero_betaraybill01	 " , char: "	Beta Ray Bill	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipShock-	" },
{ id: "	hero_bishop01	 " , char: "	Bishop	 " , suit: "	디스어셈블드	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy Projection--	" },
{ id: "	hero_blackbolt01	 " , char: "	Black Bolt	 " , suit: "	모던	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionFast Movement-	" },
{ id: "	hero_blackbolt01_S01	 " , char: "	Black Bolt	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionFast Movement-	" },
{ id: "	hero_blackbolt01_S02	 " , char: "	Black Bolt	 " , suit: "	인휴먼즈: 아틸란 라이징	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionFast Movement-	" },
{ id: "	hero_blackbolt01_S03	 " , char: "	Black Bolt	 " , suit: "	마블 엑스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionFast Movement-	" },
{ id: "	hero_blackcat01	 " , char: "	Black Cat	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Agility--	" },
{ id: "	hero_blackcat01_S01	 " , char: "	Black Cat	 " , suit: "	클로스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Agility--	" },
{ id: "	hero_blackcat01_S02	 " , char: "	Black Cat	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Agility--	" },
{ id: "	hero_blackpanther01	 " , char: "	Black Panther	 " , suit: "	모던	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandAgility-	" },
{ id: "	hero_blackpanther01_S01	 " , char: "	Black Panther	 " , suit: "	Marvel's 캡틴 아메리카: 시빌 워	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandAgility-	" },
{ id: "	hero_blackpanther01_S02	 " , char: "	Black Panther	 " , suit: "	Marvel's 블랙 팬서	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandAgility-	" },
{ id: "	hero_blackwidow01	 " , char: "	Black Widow	 " , suit: "	Marvel's 어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	hero_blackwidow01_S01	 " , char: "	Black Widow	 " , suit: "	Marvel's 어벤져스: 에이지 오브 울트론	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	hero_blackwidow01_S02	 " , char: "	Black Widow	 " , suit: "	시크릿 워즈: 2099	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	hero_blackwidow01_S03	 " , char: "	Black Widow	 " , suit: "	Marvel's 캡틴 아메리카: 시빌 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	hero_blackwidow01_S04	 " , char: "	Black Widow	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	hero_blackwidow01_S05	 " , char: "	Black Widow	 " , suit: "	Marvel's 어벤져스: 엔드게임	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	hero_blackwidow01_S06	 " , char: "	Black Widow	 " , suit: "	Marvel's 어벤져스: 엔드게임 (팀 슈트)	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	hero_blackwidow01_S07	 " , char: "	Black Widow	 " , suit: "	어벤져스 3099	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	hero_blackwidow01_S08	 " , char: "	Black Widow	 " , suit: "	Marvel's 블랙 위도우	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	hero_blackwidow01_S09	 " , char: "	Black Widow	 " , suit: "	Marvel's 블랙 위도우 (스노우 슈트)	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	hero_blade01	 " , char: "	Blade	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon MasterHealing-	" },
{ id: "	hero_blade01_S01	 " , char: "	Blade	 " , suit: "	70년대 클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon MasterHealing-	" },
{ id: "	hero_blade01_S02	 " , char: "	Blade	 " , suit: "	어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon MasterHealing-	" },
{ id: "	hero_bluedragon01	 " , char: "	Blue Dragon	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipShock-	" },
{ id: "	hero_bluemarvel01	 " , char: "	Blue Marvel	 " , suit: "	얼티미츠	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Energy ProjectionLeadership-	" },
{ id: "	hero_cable01	 " , char: "	Cable	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipWeapon Master-	" },
{ id: "	hero_cable01_S01	 " , char: "	Cable	 " , suit: "	엑스포스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipWeapon Master-	" },
{ id: "	hero_cable01_S02	 " , char: "	Cable	 " , suit: "	케이블과 데드풀	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipWeapon Master-	" },
{ id: "	hero_cable01_S03	 " , char: "	Cable	 " , suit: "	섬머 데이즈	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipWeapon Master-	" },
{ id: "	hero_captainamerica01	 " , char: "	Captain America	 " , suit: "	Marvel's 어벤져스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandLeadership-	" },
{ id: "	hero_captainamerica01_S01	 " , char: "	Captain America	 " , suit: "	Marvel's 어벤져스: 에이지 오브 울트론	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandLeadership-	" },
{ id: "	hero_captainamerica01_S02	 " , char: "	Captain America	 " , suit: "	시크릿 워즈: 2099	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandLeadership-	" },
{ id: "	hero_captainamerica01_S03	 " , char: "	Captain America	 " , suit: "	Marvel's 캡틴 아메리카: 윈터 솔져	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandLeadership-	" },
{ id: "	hero_captainamerica01_S04	 " , char: "	Captain America	 " , suit: "	Marvel's 캡틴 아메리카: 시빌 워	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandLeadership-	" },
{ id: "	hero_captainamerica01_S05	 " , char: "	Captain America	 " , suit: "	마블 나우!	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandLeadership-	" },
{ id: "	hero_captainamerica01_S06	 " , char: "	Captain America	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandLeadership-	" },
{ id: "	hero_captainamerica01_S07	 " , char: "	Captain America	 " , suit: "	Marvel's 어벤져스: 엔드게임	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandLeadership-	" },
{ id: "	hero_captainamerica01_S08	 " , char: "	Captain America	 " , suit: "	Marvel's 어벤져스: 엔드게임 (팀 슈트)	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandLeadership-	" },
{ id: "	hero_captainamerica01_S09	 " , char: "	Captain America	 " , suit: "	어벤져스 3099	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandLeadership-	" },
{ id: "	hero_captainamerica01_S10	 " , char: "	Captain America	 " , suit: "	하이드라 슈프림	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandCosmic Cube-	" },
{ id: "	hero_captainmarvel01	 " , char: "	Captain Marvel	 " , suit: "	모던	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionFast MovementLeadership	" },
{ id: "	hero_captainmarvel01_S01	 " , char: "	Captain Marvel	 " , suit: "	시크릿 워즈: 캡틴 마블과 캐럴 코어	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionFast MovementLeadership	" },
{ id: "	hero_captainmarvel01_S02	 " , char: "	Captain Marvel	 " , suit: "	미즈 마블	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionFast MovementLeadership	" },
{ id: "	hero_captainmarvel01_S03	 " , char: "	Captain Marvel	 " , suit: "	Marvel's 캡틴 마블	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionFast MovementLeadership	" },
{ id: "	hero_captainmarvel01_S04	 " , char: "	Captain Marvel	 " , suit: "	Marvel's 어벤져스: 엔드게임	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionFast MovementLeadership	" },
{ id: "	hero_clea01	 " , char: "	Clea	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Fast MovementMagic-	" },
{ id: "	hero_colossus01	 " , char: "	Colossus	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipStrong-	" },
{ id: "	hero_colossus01_S01	 " , char: "	Colossus	 " , suit: "	엑스포스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipStrong-	" },
{ id: "	hero_colossus01_S02	 " , char: "	Colossus	 " , suit: "	피닉스 파이브	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipStrong피닉스 Force	" },
{ id: "	hero_crescent01	 " , char: "	Crescent	 " , suit: "	모던	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	StrongDurabilityLeadership	" },
{ id: "	hero_crescent01_S01	 " , char: "	Crescent	 " , suit: "	라이프스타일 시리즈 1	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	StrongDurabilityLeadership	" },
{ id: "	hero_crystal01	 " , char: "	Crystal	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionCommand-	" },
{ id: "	hero_crystal01_S01	 " , char: "	Crystal	 " , suit: "	로얄 슈트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionCommand-	" },
{ id: "	hero_crystal01_S02	 " , char: "	Crystal	 " , suit: "	판타스틱 포	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Energy ProjectionCommandPotential	" },
{ id: "	hero_cyclops01	 " , char: "	Cyclops	 " , suit: "	클래식	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandEnergy Projection-	" },
{ id: "	hero_cyclops01_S01	 " , char: "	Cyclops	 " , suit: "	에이지 오브 아포칼립스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandEnergy Projection-	" },
{ id: "	hero_cyclops01_S02	 " , char: "	Cyclops	 " , suit: "	마블 나우!	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandEnergy Projection-	" },
{ id: "	hero_cyclops01_S03	 " , char: "	Cyclops	 " , suit: "	피닉스 파이브	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandEnergy Projection피닉스 Force	" },
{ id: "	hero_daisyjohnson01	 " , char: "	Daisy Johnson	 " , suit: "	Marvel's 에이전트 오브 쉴.드.	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	AgentMind Resist-	" },
{ id: "	hero_daisyjohnson01_S01	 " , char: "	Quake	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	AgentMind Resist-	" },
{ id: "	hero_daisyjohnson01_S02	 " , char: "	Daisy Johnson	 " , suit: "	Marvel's 에이전트 오브 쉴.드. (퀘이크)	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	AgentMind Resist-	" },
{ id: "	hero_daredevil01	 " , char: "	Daredevil	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipHeightened SensesAgility	" },
{ id: "	hero_daredevil01_S01	 " , char: "	Daredevil	 " , suit: "	데빌 오브 헬스 키친	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipHeightened SensesAgility	" },
{ id: "	hero_daredevil01_S02	 " , char: "	Daredevil	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipHeightened SensesAgility	" },
{ id: "	hero_darkhawk01	 " , char: "	Darkhawk	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementLeadership-	" },
{ id: "	hero_dazzler01	 " , char: "	Dazzler	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy Projection--	" },
{ id: "	hero_deadpool01	 " , char: "	Deadpool	 " , suit: "	모던	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	HealingWeapon Master-	" },
{ id: "	hero_deadpool01_S01	 " , char: "	Deadpool	 " , suit: "	엑스포스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	HealingWeapon Master-	" },
{ id: "	hero_deadpool01_S02	 " , char: "	Deadpool	 " , suit: "	레이디 데드풀	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	HealingWeapon Master-	" },
{ id: "	hero_deadpool01_S03	 " , char: "	Lady Deadpool	 " , suit: "	홀리데이 파티	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	HealingWeapon Master-	" },
{ id: "	hero_deathlok01	 " , char: "	Deathlok	 " , suit: "	Marvel's 에이전트 오브 쉴.드.	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	ShieldAgentMachine	" },
{ id: "	hero_deathlok01_S01	 " , char: "	Deathlok	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	AgentMachine-	" },
{ id: "	hero_doctorstrange01	 " , char: "	Doctor Strange	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementMagic-	" },
{ id: "	hero_doctorstrange01_S01	 " , char: "	Doctor Strange	 " , suit: "	Marvel's 닥터 스트레인지	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementMagic-	" },
{ id: "	hero_doctorstrange01_S02	 " , char: "	Doctor Strange	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementMagic-	" },
{ id: "	hero_doctorstrange01_S03	 " , char: "	Doctor Strange	 " , suit: "	Space 슈트	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementMagic-	" },
{ id: "	hero_doctorvoodoo01	 " , char: "	Doctor Voodoo	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Command--	" },
{ id: "	hero_domino01	 " , char: "	Domino	 " , suit: "	엑스포스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon MasterAgility-	" },
{ id: "	hero_domino01_S01	 " , char: "	Domino	 " , suit: "	마블 나우!	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon MasterAgility-	" },
{ id: "	hero_drax01	 " , char: "	Drax	 " , suit: "	Marvel's 가디언즈 오브 갤럭시	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	GuardiansHealing-	" },
{ id: "	hero_drax01_S01	 " , char: "	Drax	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	HealingPotential-	" },
{ id: "	hero_elektra01	 " , char: "	Elektra	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon Master--	" },
{ id: "	hero_elektra01_S01	 " , char: "	Elektra	 " , suit: "	Marvel's 데어데블	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon Master--	" },
{ id: "	hero_elsabloodstone01	 " , char: "	Elsa Bloodstone	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon Master--	" },
{ id: "	hero_elsabloodstone01_S01	 " , char: "	Elsa Bloodstone	 " , suit: "	시크릿 워즈: 마블 좀비스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon Master--	" },
{ id: "	hero_elsabloodstone01_S02	 " , char: "	Elsa Bloodstone	 " , suit: "	몬스터 언리쉬드! (MFF 배리언트)	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon Master--	" },
{ id: "	hero_emmafrost01	 " , char: "	Emma Frost	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Mind Resist--	" },
{ id: "	hero_emmafrost01_S01	 " , char: "	Emma Frost	 " , suit: "	마블 나우!	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Mind Resist--	" },
{ id: "	hero_emmafrost01_S02	 " , char: "	Emma Frost	 " , suit: "	피닉스 파이브	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityMind Resist피닉스 Force	" },
{ id: "	hero_falcon01	 " , char: "	Falcon	 " , suit: "	Marvel's 캡틴 아메리카: 윈터 솔져	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AvengersLeadershipFast Movement	" },
{ id: "	hero_falcon01_S01	 " , char: "	Falcon	 " , suit: "	올뉴 캡틴 아메리카	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipFast Movement-	" },
{ id: "	hero_falcon01_S02	 " , char: "	Falcon	 " , suit: "	Marvel's 캡틴 아메리카: 시빌 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AvengersLeadershipFast Movement	" },
{ id: "	hero_falcon01_S03	 " , char: "	Falcon	 " , suit: "	마블 레거시	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipFast Movement-	" },
{ id: "	hero_fandral01	 " , char: "	Fandral	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Agility--	" },
{ id: "	hero_fantomex01	 " , char: "	Fantomex	 " , suit: "	엑스포스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon MasterAgility-	" },
{ id: "	hero_gambit01	 " , char: "	Gambit	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	MindAgility-	" },
{ id: "	hero_gamora01	 " , char: "	Gamora	 " , suit: "	Marvel's 가디언즈 오브 갤럭시	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityWeapon Master-	" },
{ id: "	hero_gamora01_S01	 " , char: "	Gamora	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityWeapon Master-	" },
{ id: "	hero_gamora01_S02	 " , char: "	Gamora	 " , suit: "	Marvel's 가디언즈 오브 갤럭시 Vol. 2	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityWeapon Master-	" },
{ id: "	hero_ghostpanther01	 " , char: "	Ghost Panther	 " , suit: "	인피니피 워프	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Agility--	" },
{ id: "	hero_ghostrider01	 " , char: "	Ghost Rider	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Leadership--	" },
{ id: "	hero_ghostrider01_S01	 " , char: "	Ghost Rider	 " , suit: "	70년대 클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Leadership--	" },
{ id: "	hero_ghostrider01_S02	 " , char: "	Ghost Rider	 " , suit: "	인휴먼즈: 아틸란 라이징	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Leadership--	" },
{ id: "	hero_ghostrider01_S03	 " , char: "	Ghost Rider	 " , suit: "	킹 오브 헬	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Leadership--	" },
{ id: "	hero_giantman01	 " , char: "	Giant-Man	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Strong--	" },
{ id: "	hero_giantman01_S01	 " , char: "	Goliath	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Strong--	" },
{ id: "	hero_giantman01_S02	 " , char: "	Giant-Man	 " , suit: "	울트론 핌	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Strong--	" },
{ id: "	hero_gladiator01	 " , char: "	Gladiator	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipStrongFast Movement	" },
{ id: "	hero_goliath01	 " , char: "	Goliath	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityStrong-	" },
{ id: "	hero_gorgon01	 " , char: "	Gorgon	 " , suit: "	워 오브 킹즈	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Strong--	" },
{ id: "	hero_gorillaman01	 " , char: "	Gorilla-Man	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	StrongAgilityWeapon Master	" },
{ id: "	hero_groot01	 " , char: "	Groot	 " , suit: "	Marvel's 가디언즈 오브 갤럭시	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Healing--	" },
{ id: "	hero_groot01_S01	 " , char: "	Groot	 " , suit: "	시크릿 워즈: Thors	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Healing--	" },
{ id: "	hero_groot01_S02	 " , char: "	Groot	 " , suit: "	Marvel's 가디언즈 오브 갤럭시 Vol. 2	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Healing--	" },
{ id: "	hero_groot01_S03	 " , char: "	Groot	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Healing--	" },
{ id: "	hero_gwenpool01	 " , char: "	Gwenpool	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Agility--	" },
{ id: "	hero_gwenpool01_S01	 " , char: "	Gwenpool	 " , suit: "	그웬 풀	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Agility--	" },
{ id: "	hero_gwenpool01_S02	 " , char: "	Gwenpool	 " , suit: "	홀리데이 파티	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Agility--	" },
{ id: "	hero_hawkeye01	 " , char: "	Hawkeye	 " , suit: "	Marvel's 어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentWeapon Master-	" },
{ id: "	hero_hawkeye01_S01	 " , char: "	Hawkeye	 " , suit: "	Marvel's 어벤져스: 에이지 오브 울트론	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentWeapon Master-	" },
{ id: "	hero_hawkeye01_S02	 " , char: "	Hawkeye	 " , suit: "	Marvel's 캡틴 아메리카: 시빌 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentWeapon Master-	" },
{ id: "	hero_hawkeye01_S03	 " , char: "	Hawkeye	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentWeapon Master-	" },
{ id: "	hero_hawkeye01_S04	 " , char: "	Ronin	 " , suit: "	Marvel's 어벤져스: 엔드게임	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentWeapon Master-	" },
{ id: "	hero_heimdall01	 " , char: "	Heimdall	 " , suit: "	Marvel's 토르: 라그나로크	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Strong--	" },
{ id: "	hero_hellcat01	 " , char: "	Hellcat	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Agility--	" },
{ id: "	hero_hellstorm01	 " , char: "	Hellstorm	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Magic--	" },
{ id: "	hero_hogun01	 " , char: "	Hogun	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Strong--	" },
{ id: "	hero_hulk01	 " , char: "	Hulk	 " , suit: "	Marvel's 어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Gamma RadiationDurability-	" },
{ id: "	hero_hulk01_S01	 " , char: "	Hulk	 " , suit: "	시크릿 워즈: 퓨처 임퍼펙트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Durability--	" },
{ id: "	hero_hulk01_S02	 " , char: "	Hulk	 " , suit: "	월드 워 헐크	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Durability--	" },
{ id: "	hero_hulk01_S03	 " , char: "	Hulk	 " , suit: "	Marvel's 토르: 라그나로크	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Gamma RadiationDurability-	" },
{ id: "	hero_hulk01_S04	 " , char: "	Hulk	 " , suit: "	Marvel's 어벤져스: 엔드게임	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Gamma RadiationDurability-	" },
{ id: "	hero_hulk01_S05	 " , char: "	Hulk	 " , suit: "	Marvel's 어벤져스: 엔드게임 (팀 슈트)	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Gamma RadiationDurability-	" },
{ id: "	hero_hulk01_S06	 " , char: "	Hulk	 " , suit: "	이모탈	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Durability--	" },
{ id: "	hero_hulkbuster01	 " , char: "	헐크버스터 (Iron Mark Mark 44)	 " , suit: "	Marvel's 어벤져스: 에이지 오브 울트론	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	MachineStrong-	" },
{ id: "	hero_hulkbuster01_S01	 " , char: "	헐크버스터 (Iron Mark Mark 43)	 " , suit: "	헤비 듀티 아머	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	MachineStrong-	" },
{ id: "	hero_hulkbuster01_S02	 " , char: "	헐크버스터 2.0	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	MachineStrong-	" },
{ id: "	hero_hulkling01	 " , char: "	Hulkling	 " , suit: "	뉴 어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Strong--	" },
{ id: "	hero_humantorch01	 " , char: "	Human Torch	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementFlame-	" },
{ id: "	hero_humantorch01_S01	 " , char: "	Human Torch	 " , suit: "	퓨처 파운데이션	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementFlame-	" },
{ id: "	hero_hyperion01	 " , char: "	Hyperion	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Leadership--	" },
{ id: "	hero_hyperion01_S01	 " , char: "	Hyperion	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Leadership--	" },
{ id: "	hero_iceman01	 " , char: "	Iceman	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	ChillCold Blooded-	" },
{ id: "	hero_iceman01_S01	 " , char: "	Iceman	 " , suit: "	엑스맨 블루	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	ChillCold Blooded-	" },
{ id: "	hero_inferno01	 " , char: "	Inferno	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Flame--	" },
{ id: "	hero_inferno01_S01	 " , char: "	Inferno	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Flame--	" },
{ id: "	hero_invisiblewoman01	 " , char: "	Invisible Woman	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy Projection--	" },
{ id: "	hero_invisiblewoman01_S01	 " , char: "	Invisible Woman	 " , suit: "	퓨처 파운데이션	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy Projection--	" },
{ id: "	hero_ironfist01	 " , char: "	Iron Fist	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	HealingAgility-	" },
{ id: "	hero_ironfist01_S01	 " , char: "	Iron Fist	 " , suit: "	뉴 어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	HealingAgility-	" },
{ id: "	hero_ironfist01_S02	 " , char: "	Iron Fist	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	HealingAgility-	" },
{ id: "	hero_ironfist01_S03	 " , char: "	Iron Fist	 " , suit: "	Marvel's 아이언 피스트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	DefendersHealingAgility	" },
{ id: "	hero_ironhammer01	 " , char: "	Iron Hammer	 " , suit: "	인피니피 워프	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	ShockMachine-	" },
{ id: "	hero_ironheart01	 " , char: "	Ironheart	 " , suit: "	마블 나우!	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	LeadershipMachine-	" },
{ id: "	hero_ironman01	 " , char: "	Iron Man	 " , suit: "	Marvel's 어벤져스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionMachine-	" },
{ id: "	hero_ironman01_S01	 " , char: "	Iron Man	 " , suit: "	Marvel's 어벤져스: 에이지 오브 울트론	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionMachine-	" },
{ id: "	hero_ironman01_S02	 " , char: "	Iron Man	 " , suit: "	시크릿 워즈: 2099	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionMachine-	" },
{ id: "	hero_ironman01_S03	 " , char: "	Iron Man	 " , suit: "	Marvel's 캡틴 아메리카: 시빌 워	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionMachine-	" },
{ id: "	hero_ironman01_S04	 " , char: "	Iron Man	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionMachine-	" },
{ id: "	hero_ironman01_S05	 " , char: "	Iron Man	 " , suit: "	Marvel's 어벤져스: 엔드게임	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionMachine-	" },
{ id: "	hero_ironman01_S06	 " , char: "	Iron Man	 " , suit: "	Marvel's 어벤져스: 엔드게임 (팀 슈트)	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionMachine-	" },
{ id: "	hero_ironman01_S07	 " , char: "	Iron Man	 " , suit: "	어벤져스 3099	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionMachine-	" },
{ id: "	hero_janefoster01	 " , char: "	Thor (Jane Foster)	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Fast MovementShock-	" },
{ id: "	hero_jeangrey01	 " , char: "	Jean Grey	 " , suit: "	피닉스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	피닉스 ForceMindMind Resist	" },
{ id: "	hero_jeangrey01_S01	 " , char: "	Jean Grey	 " , suit: "	엑스맨 레드	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	피닉스 ForceMindMind Resist	" },
{ id: "	hero_jeangrey01_S02	 " , char: "	Jean Grey	 " , suit: "	마블 걸	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	피닉스 ForceMindMind Resist	" },
{ id: "	hero_jessicajones01	 " , char: "	Jessica Jones	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	DurabilityStrong-	" },
{ id: "	hero_jubilee01	 " , char: "	Jubilee	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Energy ProjectionPotential-	" },
{ id: "	hero_kamalakhan01	 " , char: "	Ms. Marvel (Kamala Khan)	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	StrongPotential-	" },
{ id: "	hero_kamalakhan01_S01	 " , char: "	Ms. Marvel (Kamala Khan)	 " , suit: "	카라치 코스튬	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	StrongPotential-	" },
{ id: "	hero_kamalakhan01_S02	 " , char: "	Ms. Marvel (Kamala Khan)	 " , suit: "	인휴먼즈: 아틸란 라이징	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	StrongPotential-	" },
{ id: "	hero_karnak01	 " , char: "	Karnak	 " , suit: "	워 오브 킹즈	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Heightened Senses--	" },
{ id: "	hero_karnak01_S01	 " , char: "	Karnak	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Heightened Senses--	" },
{ id: "	hero_katebishop01	 " , char: "	Hawkeye (Kate Bishop)	 " , suit: "	마블 나우!	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	AgentAgility-	" },
{ id: "	hero_kidkaiju01	 " , char: "	Kid Kaiju	 " , suit: "	몬스터 언리쉬드!	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Command--	" },
{ id: "	hero_kidkaiju01_S01	 " , char: "	Kid Kaiju	 " , suit: "	몬스터 언리쉬드! (MFF 배리언트)	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Command--	" },
{ id: "	hero_kidomega01	 " , char: "	Kid Omega	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	피닉스 ForceEnergy Projection-	" },
{ id: "	hero_kittypryde01	 " , char: "	Kitty Pryde	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandWeapon Master-	" },
{ id: "	hero_lincoln01	 " , char: "	Lincoln Campbell	 " , suit: "	Marvel's 에이전트 오브 쉴.드.	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Shock--	" },
{ id: "	hero_lukecage01	 " , char: "	Luke Cage	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	DurabilityStrong-	" },
{ id: "	hero_lukecage01_S01	 " , char: "	Luke Cage	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	DurabilityStrong-	" },
{ id: "	hero_lukecage01_S02	 " , char: "	Luke Cage	 " , suit: "	Marvel's 루크 케이지	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	DurabilityStrong-	" },
{ id: "	hero_lunasnow01	 " , char: "	Luna Snow	 " , suit: "	모던	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Cold BloodedLeadership-	" },
{ id: "	hero_lunasnow01_S01	 " , char: "	Luna Snow	 " , suit: "	안드로메다 슈트	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Cold BloodedLeadership-	" },
{ id: "	hero_lunasnow01_S02	 " , char: "	Luna Snow	 " , suit: "	라이프스타일 시리즈 1	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Cold BloodedLeadership-	" },
{ id: "	hero_magik01	 " , char: "	Magik	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	MagicMind Resist-	" },
{ id: "	hero_magik01_S01	 " , char: "	Magik	 " , suit: "	피닉스 파이브	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	MagicMind Resist피닉스 Force	" },
{ id: "	hero_mantis01	 " , char: "	Mantis	 " , suit: "	Marvel's 가디언즈 오브 갤럭시 Vol. 2	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	HealingMind-	" },
{ id: "	hero_medusa01	 " , char: "	Medusa	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Command--	" },
{ id: "	hero_medusa01_S01	 " , char: "	Medusa	 " , suit: "	몬스터 언리쉬드! (MFF 배리언트)	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Command--	" },
{ id: "	hero_medusa01_S02	 " , char: "	Medusa	 " , suit: "	인휴먼즈 대 엑스맨	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Command--	" },
{ id: "	hero_milesmorales01	 " , char: "	Spider-Man (Miles Morales)	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipAgilitySpider-Sense	" },
{ id: "	hero_milesmorales01_S01	 " , char: "	Spider-Man (Miles Morales)	 " , suit: "	인투 더 스파이더버스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipAgilitySpider-Sense	" },
{ id: "	hero_misterfantastic01	 " , char: "	Misty Knight	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon MasterAgent-	" },
{ id: "	hero_misterfantastic01_S01	 " , char: "	Mister Fantastic	 " , suit: "	모던	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityLeadership-	" },
{ id: "	hero_mistyknight01	 " , char: "	Mister Sinister	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	HealingEnergy Projection-	" },
{ id: "	hero_mockingbird01	 " , char: "	Mockingbird	 " , suit: "	영웅 시대	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	hero_mockingbird01_S01	 " , char: "	Bobbi Morse	 " , suit: "	Marvel's 에이전트 오브 쉴.드. (바비 모스)	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	ShieldAgentAgility	" },
{ id: "	hero_mockingbird01_S02	 " , char: "	Mockingbird	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	hero_moongirl01	 " , char: "	Moon Girl	 " , suit: "	마블 나우!	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	hero_moongirl01_S01	 " , char: "	Moon Girl	 " , suit: "	몬스터 언리쉬드!	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	hero_moonknight01	 " , char: "	Moon Knight	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon Master--	" },
{ id: "	hero_moonknight01_S01	 " , char: "	Moon Knight	 " , suit: "	아머드	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon Master--	" },
{ id: "	hero_moonknight01_S02	 " , char: "	Moon Knight	 " , suit: "	미스터 나이트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon Master--	" },
{ id: "	hero_nadiapym01	 " , char: "	Wasp (Nadia Van Dyne)	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Fast Movement--	" },
{ id: "	hero_namor01	 " , char: "	Namor	 " , suit: "	클래식	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Strong--	" },
{ id: "	hero_namor01_S01	 " , char: "	Namor	 " , suit: "	피닉스 파이브	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityStrong피닉스 Force	" },
{ id: "	hero_negasonic01	 " , char: "	Negasonic Teenage Warhead	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityFast MovementEnergy Projection	" },
{ id: "	hero_nickfury01	 " , char: "	Nick Fury	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon MasterLeadershipAgent	" },
{ id: "	hero_nickfury01_S01	 " , char: "	Nick Fury	 " , suit: "	Marvel's 캡틴 마블	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon MasterLeadershipAgent	" },
{ id: "	hero_nicominoru01	 " , char: "	Sister Grimm	 " , suit: "	시크릿 워즈: 에이포스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Magic--	" },
{ id: "	hero_nicominoru01_S01	 " , char: "	Sister Grimm	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Magic--	" },
{ id: "	hero_nightcrawler01	 " , char: "	Nightcrawler	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipAgility-	" },
{ id: "	hero_nightcrawler01_S01	 " , char: "	Nightcrawler	 " , suit: "	엑스포스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipAgility-	" },
{ id: "	hero_nova01	 " , char: "	Nova (Sam Alexander)	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Fast Movement-	" },
{ id: "	hero_odin01	 " , char: "	Odin	 " , suit: "	모던	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionCommand-	" },
{ id: "	hero_odin01_S01	 " , char: "	Odin	 " , suit: "	All-Father	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionCommand-	" },
{ id: "	hero_philcoulson01	 " , char: "	Phil Coulson	 " , suit: "	Marvel's 에이전트 오브 쉴.드.	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	ShieldAgentCommand	" },
{ id: "	hero_philcoulson01_S01	 " , char: "	Phil Coulson	 " , suit: "	Marvel's 에이전트 오브 쉴.드. 시즌 3	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	ShieldAgentCommand	" },
{ id: "	hero_phylavell01	 " , char: "	Phyla-Vell	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipEnergy Projection-	" },
{ id: "	hero_professorx01	 " , char: "	Professor X	 " , suit: "	모던	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipMindMind Resist	" },
{ id: "	hero_psylocke01	 " , char: "	Psylocke	 " , suit: "	엑스포스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	MindAgility-	" },
{ id: "	hero_psylocke01_S01	 " , char: "	Psylocke	 " , suit: "	디스어셈블드	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	MindAgility-	" },
{ id: "	hero_punisher01	 " , char: "	Punisher	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon MasterLeadership-	" },
{ id: "	hero_punisher01_S01	 " , char: "	Punisher	 " , suit: "	느와르	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon MasterLeadership-	" },
{ id: "	hero_punisher01_S02	 " , char: "	Punisher	 " , suit: "	워 저널	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon MasterLeadership-	" },
{ id: "	hero_punisher01_S03	 " , char: "	Punisher	 " , suit: "	Marvel's 데어데블	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon MasterLeadership-	" },
{ id: "	hero_punisher01_S04	 " , char: "	Punisher	 " , suit: "	마블 레거시	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipWeapon MasterMachine	" },
{ id: "	hero_punisher01_S05	 " , char: "	Punisher	 " , suit: "	코스믹 고스트 라이더	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	FlamePower Cosmic-	" },
{ id: "	hero_quasar01	 " , char: "	Quasar (Avril Kincaid)	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Heightened Senses--	" },
{ id: "	hero_quicksilver01	 " , char: "	Quicksilver	 " , suit: "	클래식	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityFast Movement-	" },
{ id: "	hero_quicksilver01_S01	 " , char: "	Quicksilver	 " , suit: "	마블 레거시	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityFast Movement-	" },
{ id: "	hero_quicksilver01_S02	 " , char: "	Quicksilver	 " , suit: "	언캐니 어벤져스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityFast Movement-	" },
{ id: "	hero_rachelsummers01	 " , char: "	Rachel Summers	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast Movement--	" },
{ id: "	hero_redshehulk01	 " , char: "	Red She-Hulk	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityFlame-	" },
{ id: "	hero_rescue01	 " , char: "	Rescue	 " , suit: "	Marvel's 어벤져스: 엔드게임	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AvengersLeadershipMachine	" },
{ id: "	hero_richardrider01	 " , char: "	Nova (Richard Rider)	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionFast Movement-	" },
{ id: "	hero_robbiereyes01	 " , char: "	Ghost Rider (Robbie Reyes)	 " , suit: "	마블 나우!	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Fast Movement--	" },
{ id: "	hero_rocketraccoon01	 " , char: "	Rocket Raccoon	 " , suit: "	Marvel's 가디언즈 오브 갤럭시	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	hero_rocketraccoon01_S01	 " , char: "	Rocket Raccoon	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	hero_rocketraccoon01_S02	 " , char: "	Rocket Raccoon	 " , suit: "	Marvel's 가디언즈 오브 갤럭시 Vol. 2	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	hero_rocketraccoon01_S03	 " , char: "	Rocket Raccoon	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	hero_rocketraccoon01_S04	 " , char: "	Rocket Raccoon	 " , suit: "	Marvel's 어벤져스: 엔드게임	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	hero_rocketraccoon01_S05	 " , char: "	Rocket Raccoon	 " , suit: "	Marvel's 어벤져스: 엔드게임 (팀 슈트)	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	hero_rogue01	 " , char: "	Rogue	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementHealing-	" },
{ id: "	hero_rogue01_S01	 " , char: "	Rogue	 " , suit: "	에이지 오브 아포칼립스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementHealing-	" },
{ id: "	hero_rogue01_S02	 " , char: "	Rogue	 " , suit: "	언캐니 어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementHealing-	" },
{ id: "	hero_satana01	 " , char: "	Satana	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Magic--	" },
{ id: "	hero_satana01_S01	 " , char: "	Satana	 " , suit: "	마블 레거시	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Magic--	" },
{ id: "	hero_scarletspider01	 " , char: "	Scarlet Spider	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "		" },
{ id: "	hero_scarletwitch01	 " , char: "	Scarlet Witch	 " , suit: "	클래식	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast Movement--	" },
{ id: "	hero_scarletwitch01_S01	 " , char: "	Scarlet Witch	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Chaos Magic--	" },
{ id: "	hero_scarletwitch01_S02	 " , char: "	Scarlet Witch	 " , suit: "	언캐니 어벤져스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AvengersFast MovementChaos Magic	" },
{ id: "	hero_scarletwitch01_S03	 " , char: "	Scarlet Witch	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementChaos Magic-	" },
{ id: "	hero_shadowshell01	 " , char: "	Shadow Shell	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementChaos Magic-	" },
{ id: "	hero_shangchi01	 " , char: "	Shang Chi	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityPoison-	" },
{ id: "	hero_sharoncarter01	 " , char: "	Agent 13	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	AgentLeadershipAgility	" },
{ id: "	hero_sharoncarter01_S01	 " , char: "	Agent 13	 " , suit: "	Marvel's 캡틴 아메리카: 시빌 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipAgility-	" },
{ id: "	hero_sharonrogers01	 " , char: "	Captain America (Sharon Rogers)	 " , suit: "	캡틴 아메리카 75주년 기념	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionAgent-	" },
{ id: "	hero_sharonrogers01_S01	 " , char: "	Captain America (Sharon Rogers)	 " , suit: "	스타라이트 아머	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionLeadership-	" },
{ id: "	hero_sharonrogers01_S02	 " , char: "	Captain America (Sharon Rogers)	 " , suit: "	다크 스타 아머	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionLeadership-	" },
{ id: "	hero_sharonrogers01_S03	 " , char: "	Captain America (Sharon Rogers)	 " , suit: "	스타 나이트 아머 	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionLeadership-	" },
{ id: "	hero_shehulk01	 " , char: "	She-Hulk	 " , suit: "	시크릿 워즈: 에이포스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	DurabilityPotential-	" },
{ id: "	hero_shehulk01_S01	 " , char: "	She-Hulk	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	DurabilityPotential-	" },
{ id: "	hero_shehulk01_S02	 " , char: "	She-Hulk	 " , suit: "	판타스틱 포	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Gamma RadiationDurability-	" },
{ id: "	hero_shehulk01_S03	 " , char: "	She-Hulk	 " , suit: "	어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	DurabilityPotential-	" },
{ id: "	hero_shuri01	 " , char: "	Shuri	 " , suit: "	마블 레거시	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Heightened Senses--	" },
{ id: "	hero_shuri01_S01	 " , char: "	Shuri	 " , suit: "	Marvel's 블랙 팬서	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipHeightened Senses-	" },
{ id: "	hero_sif01	 " , char: "	Sif	 " , suit: "	Marvel's 에이전트 오브 쉴.드.	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Agility--	" },
{ id: "	hero_sif01_S01	 " , char: "	Sif	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Agility--	" },
{ id: "	hero_silk01	 " , char: "	Silk	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilitySpider-Sense-	" },
{ id: "	hero_silk01_S01	 " , char: "	Silk	 " , suit: "	웹 슈트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilitySpider-Sense-	" },
{ id: "	hero_silversurfer01	 " , char: "	Silver Surfer	 " , suit: "	모던	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Power Cosmic--	" },
{ id: "	hero_silversurfer01_S01	 " , char: "	Silver Surfer	 " , suit: "	블랙	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Power Cosmic--	" },
{ id: "	hero_singularity01	 " , char: "	Singularity	 " , suit: "	시크릿 워즈: 에이포스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Energy ProjectionFast Movement-	" },
{ id: "	hero_slapstick01	 " , char: "	Slapstick	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Agility--	" },
{ id: "	hero_songbird01	 " , char: "	Songbird	 " , suit: "	뉴 어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast Movement--	" },
{ id: "	hero_spidergwen01	 " , char: "	Spider-Gwen	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	LeadershipAgilitySpider-Sense	" },
{ id: "	hero_spidergwen01_S01	 " , char: "	Spider-Gwen	 " , suit: "	그웬돌린 스테이시	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	LeadershipAgilitySpider-Sense	" },
{ id: "	hero_spiderman01	 " , char: "	Spider-Man	 " , suit: "	클래식	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityLeadershipSpider-Sense	" },
{ id: "	hero_spiderman01_S01	 " , char: "	Spider-Man	 " , suit: "	시크릿 워즈: 리뉴 유어 바우	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityLeadershipSpider-Sense	" },
{ id: "	hero_spiderman01_S02	 " , char: "	Spider-Man	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityLeadershipSpider-Sense	" },
{ id: "	hero_spiderman01_S03	 " , char: "	Spider-Man	 " , suit: "	Marvel's 캡틴 아메리카: 시빌 워	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityLeadershipSpider-Sense	" },
{ id: "	hero_spiderman01_S04	 " , char: "	Spider-Man	 " , suit: "	Marvel's 스파이더맨: 홈커밍 (홈메이드 슈트)	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityLeadershipSpider-Sense	" },
{ id: "	hero_spiderman01_S05	 " , char: "	Spider-Man	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityLeadershipSpider-Sense	" },
{ id: "	hero_spiderman01_S06	 " , char: "	Spider-Man	 " , suit: "	Marvel's 스파이더맨: 파 프롬 홈	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityLeadershipSpider-Sense	" },
{ id: "	hero_spiderman01_S07	 " , char: "	Spider-Man	 " , suit: "	Marvel's 스파이더맨: 파 프롬 홈 (스텔스 슈트)	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityLeadershipSpider-Sense	" },
{ id: "	hero_spiderman209901	 " , char: "	Spider-Man 2099	 " , suit: "	모던	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityLeadershipSpider-Sense	" },
{ id: "	hero_spiderman209901_S01	 " , char: "	Spider-Man 2099	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityLeadershipSpider-Sense	" },
{ id: "	hero_squirrelgirl01	 " , char: "	Squirrel Girl	 " , suit: "	뉴 어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Agility--	" },
{ id: "	hero_squirrelgirl01_S01	 " , char: "	Squirrel Girl	 " , suit: "	마블 나우!	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Agility--	" },
{ id: "	hero_starlord01	 " , char: "	Star-Lord	 " , suit: "	Marvel's 가디언즈 오브 갤럭시	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandWeapon Master-	" },
{ id: "	hero_starlord01_S01	 " , char: "	Star-Lord	 " , suit: "	스페이스 아머	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandWeapon Master-	" },
{ id: "	hero_starlord01_S02	 " , char: "	Star-Lord	 " , suit: "	Marvel's 가디언즈 오브 갤럭시 Vol. 2	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandWeapon Master-	" },
{ id: "	hero_starlord01_S03	 " , char: "	Star-Lord	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandWeapon Master-	" },
{ id: "	hero_starlord01_S04	 " , char: "	Star-Lord	 " , suit: "	Grounded	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandWeapon Master-	" },
{ id: "	hero_storm01	 " , char: "	Storm	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandShock-	" },
{ id: "	hero_storm01_S01	 " , char: "	Storm	 " , suit: "	엑스맨 레드	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandShock-	" },
{ id: "	hero_storm01_S02	 " , char: "	Storm	 " , suit: "	인휴먼즈 대 엑스맨	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandShock-	" },
{ id: "	hero_sunbird01	 " , char: "	Sun Bird	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityFlame-	" },
{ id: "	hero_swordmaster01	 " , char: "	Sword Master	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipWeapon Master-	" },
{ id: "	hero_thing01	 " , char: "	Thing	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityStrong-	" },
{ id: "	hero_thing01_S01	 " , char: "	Thing	 " , suit: "	퓨처 파운데이션	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityStrong-	" },
{ id: "	hero_thor01	 " , char: "	Thor	 " , suit: "	Marvel's 어벤져스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipShock-	" },
{ id: "	hero_thor01_S01	 " , char: "	Thor	 " , suit: "	Marvel's 어벤져스: 에이지 오브 울트론	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipShock-	" },
{ id: "	hero_thor01_S02	 " , char: "	Thor	 " , suit: "	Unworthy	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipShock-	" },
{ id: "	hero_thor01_S03	 " , char: "	Thor	 " , suit: "	Marvel's 토르: 라그나로크	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipShock-	" },
{ id: "	hero_thor01_S04	 " , char: "	Thor	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipShock-	" },
{ id: "	hero_thor01_S05	 " , char: "	Thor	 " , suit: "	Marvel's 어벤져스: 엔드게임	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipShock-	" },
{ id: "	hero_thor01_S06	 " , char: "	Thor	 " , suit: "	Marvel's 어벤져스: 엔드게임 (팀 슈트)	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipShock-	" },
{ id: "	hero_valkyrie01	 " , char: "	Valkyrie	 " , suit: "	Marvel's 토르: 라그나로크	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Strong--	" },
{ id: "	hero_vision01	 " , char: "	Vision	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementMachine-	" },
{ id: "	hero_vision01_S01	 " , char: "	Vision	 " , suit: "	Marvel's 어벤져스: 에이지 오브 울트론	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityFast MovementMachine	" },
{ id: "	hero_vision01_S02	 " , char: "	Vision	 " , suit: "	언캐니 어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityFast MovementMachine	" },
{ id: "	hero_volstagg01	 " , char: "	Volstagg	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Durability--	" },
{ id: "	hero_warmachine01	 " , char: "	War Machine	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipMachine-	" },
{ id: "	hero_warmachine01_S01	 " , char: "	War Machine	 " , suit: "	아이언 패트리어트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipMachine-	" },
{ id: "	hero_warmachine01_S02	 " , char: "	War Machine	 " , suit: "	어벤져스: 이니셔티브	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipMachine-	" },
{ id: "	hero_warmachine01_S03	 " , char: "	War Machine	 " , suit: "	Marvel's 캡틴 아메리카: 시빌 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipMachine-	" },
{ id: "	hero_warmachine01_S04	 " , char: "	War Machine	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipMachine-	" },
{ id: "	hero_warmachine01_S05	 " , char: "	War Machine	 " , suit: "	Marvel's 어벤져스: 엔드게임	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipMachine-	" },
{ id: "	hero_warmachine01_S06	 " , char: "	War Machine	 " , suit: "	Marvel's 어벤져스: 엔드게임 (팀 슈트)	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipMachine-	" },
{ id: "	hero_warpath01	 " , char: "	Warpath	 " , suit: "	엑스포스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipStrong-	" },
{ id: "	hero_wartiger01	 " , char: "	War Tiger	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	StrongDurability-	" },
{ id: "	hero_warwolf01	 " , char: "	Warwolf	 " , suit: "	하울링 코만도스 오브 쉴.드.	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentHealing-	" },
{ id: "	hero_wasp01	 " , char: "	Wasp	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast Movement--	" },
{ id: "	hero_wasp01_S01	 " , char: "	Wasp	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast Movement--	" },
{ id: "	hero_wasp01_S02	 " , char: "	Wasp	 " , suit: "	Marvel's 앤트맨과 와스프	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast Movement--	" },
{ id: "	hero_wave01	 " , char: "	Wave	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityHeightened Senses-	" },
{ id: "	hero_weaponhex01	 " , char: "	Weapon Hex	 " , suit: "	인피니피 워프	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Chaos MagicHealingAgility	" },
{ id: "	hero_whitefox01	 " , char: "	White Fox	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipAgility-	" },
{ id: "	hero_whitefox01_S01	 " , char: "	White Fox	 " , suit: "	라이프스타일 시리즈 1	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	LeadershipAgility-	" },
{ id: "	hero_whitetiger01	 " , char: "	White Tiger	 " , suit: "	뉴 어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "Potential	--	" },
{ id: "	hero_wiccan01	 " , char: "	Wiccan	 " , suit: "	뉴 어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionFast Movement-	" },
{ id: "	hero_wintersoldier01	 " , char: "	Winter Soldier	 " , suit: "	Marvel's 캡틴 아메리카: 윈터 솔져	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	hero_wintersoldier01_S01	 " , char: "	Winter Soldier	 " , suit: "	Marvel's 캡틴 아메리카: 시빌 워	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	hero_wintersoldier01_S02	 " , char: "	Winter Soldier	 " , suit: "	캡틴 아메리카	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	hero_wintersoldier01_S03	 " , char: "	Winter Soldier	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AvengersWeapon Master-	" },
{ id: "	hero_wolverine01	 " , char: "	Wolverine	 " , suit: "	클래식	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	HealingWeapon Master-	" },
{ id: "	hero_wolverine01_S01	 " , char: "	Wolverine	 " , suit: "	에이지 오브 아포칼립스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	HealingWeapon Master-	" },
{ id: "	hero_wolverine01_S02	 " , char: "	Wolverine	 " , suit: "	올뉴 마블 나우!	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	HealingWeapon Master-	" },
{ id: "	hero_wolverine01_S03	 " , char: "	Wolverine	 " , suit: "	엑스포스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	HealingWeapon Master-	" },
{ id: "	hero_wolverine01_S04	 " , char: "	Wolverine	 " , suit: "	하우스 오브 엑스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	HealingWeapon Master-	" },
{ id: "	hero_wong01	 " , char: "	Wong	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master-	" },
{ id: "	hero_wong01_S01	 " , char: "	Wong	 " , suit: "	Marvel's 닥터 스트레인지	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master-	" },
{ id: "	hero_x-2301	 " , char: "	X-23	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	HealingAgility-	" },
{ id: "	hero_x-2301_S01	 " , char: "	X-23	 " , suit: "	엑스포스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	HealingAgility-	" },
{ id: "	sv_abomination01	 " , char: "	Abomination	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Gamma RadiationDurability-	" },
{ id: "	sv_absorbingman01	 " , char: "	Absorbing Man	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Strong--	" },
{ id: "	sv_antiman01	 " , char: "	Anti-Man	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Energy ProjectionFast Movement-	" },
{ id: "	sv_apocalypse01	 " , char: "	Apocalypse	 " , suit: "	에이지 오브 아포칼립스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityFast MovementPure Evil	" },
{ id: "	sv_apocalypse01_S01	 " , char: "	Apocalypse	 " , suit: "	메시아 콤플렉스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityFast MovementPure Evil	" },
{ id: "	sv_baronmordo01	 " , char: "	Baron Mordo	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Pure EvilMagic-	" },
{ id: "	sv_baronmordo01_S01	 " , char: "	Mordo	 " , suit: "	Marvel's 닥터 스트레인지	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Heightened SensesAgility-	" },
{ id: "	sv_baronzemo01	 " , char: "	Baron Zemo	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	--	" },
{ id: "	sv_blackdwarf01	 " , char: "	Black Dwarf	 " , suit: "	인피니티	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityStrong-	" },
{ id: "	sv_blackdwarf01_S01	 " , char: "	Cull Obsidian	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Black OrderDurabilityStrong	" },
{ id: "	sv_bullseye01	 " , char: "	Bullseye	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	sv_bullseye01_S01	 " , char: "	Bullseye	 " , suit: "	시크릿 워즈: 1872	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	sv_carnage01	 " , char: "	Carnage	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	HealingSymbiote-	" },
{ id: "	sv_corvusglaive01	 " , char: "	Corvus Glaive	 " , suit: "	인피니티	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementAgility-	" },
{ id: "	sv_corvusglaive01_S01	 " , char: "	Corvus Glaive	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Black OrderFast MovementAgility	" },
{ id: "	sv_crossbones01	 " , char: "	Crossbones	 " , suit: "	Marvel's 캡틴 아메리카: 시빌 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	sv_crossbones01_S01	 " , char: "	Crossbones	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	sv_crossbones01_S02	 " , char: "	Crossbones	 " , suit: "	시크릿 엠파이어	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon Master--	" },
{ id: "	sv_destroyer01	 " , char: "	Destroyer	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Flame--	" },
{ id: "	sv_destroyer01_S01	 " , char: "	Destroyer	 " , suit: "	프로메티우스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Flame--	" },
{ id: "	sv_doctordoom01	 " , char: "	Doctor Doom	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	MagicPure Evil-	" },
{ id: "	sv_doctorminerva01	 " , char: "	Minn-Erva	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilDurabilityStrong	" },
{ id: "	sv_doctorminerva01_S01	 " , char: "	Minn-Erva	 " , suit: "	Marvel's 캡틴 마블	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilDurabilityStrong	" },
{ id: "	sv_doctoroctopus01	 " , char: "	Doctor Octopus	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityMachine Sinister Six	" },
{ id: "	sv_doctoroctopus01_S01	 " , char: "	Doctor Octopus	 " , suit: "	슈피리어 스파이더맨	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityMachineSpider-Sense	" },
{ id: "	sv_doctoroctopus01_S02	 " , char: "	Doctor Octopus	 " , suit: "	슈피리어 옥토퍼스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	AgilityMachine Sinister Six	" },
{ id: "	sv_dormmamu01	 " , char: "	Dormammu	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Magic--	" },
{ id: "	sv_dormmamu01	 " , char: "	Dormammu	 " , suit: "	댐네이션	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Magic--	" },
{ id: "	sv_ebonymaw01	 " , char: "	Ebony Maw	 " , suit: "	인피니티	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementMind ResistPure Evil	" },
{ id: "	sv_ebonymaw01_S01	 " , char: "	Ebony Maw	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementMind ResistPure Evil	" },
{ id: "	sv_electro01	 " , char: "	Electro	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilShockSinister Six	" },
{ id: "	sv_enchantress01	 " , char: "	Enchantress	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	MindMagic-	" },
{ id: "	sv_enchantress01_S01	 " , char: "	Enchantress	 " , suit: "	섬머 데이즈	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	MindMagic-	" },
{ id: "	sv_ghost01	 " , char: "	Ghost	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	MachineWeapon Master-	" },
{ id: "	sv_ghost01_S01	 " , char: "	Ghost	 " , suit: "	Marvel's 앤트맨과 와스프	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	MachineWeapon Master-	" },
{ id: "	sv_greengoblin01	 " , char: "	Green Goblin	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementPoison-	" },
{ id: "	sv_greengoblin01_S01	 " , char: "	Green Goblin	 " , suit: "	얼티밋	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast MovementFlame-	" },
{ id: "	sv_hela01	 " , char: "	Hela	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Pure EvilCommand-	" },
{ id: "	sv_hela01_S01	 " , char: "	Hela	 " , suit: "	Marvel's 토르: 라그나로크	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	AsgardPure EvilCommand	" },
{ id: "	sv_hydroman01	 " , char: "	Hydro-Man	 " , suit: "	Marvel's 스파이더맨: 파 프롬 홈	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Pure EvilPotential-	" },
{ id: "	sv_juggernaut01	 " , char: "	Juggernaut	 " , suit: "	브라더후드 오브 뮤턴츠	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	StrongDurabilityPure Evil	" },
{ id: "	sv_kaecilius01	 " , char: "	Kaecilius	 " , suit: "	Marvel's 닥터 스트레인지	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	AgilityMagic-	" },
{ id: "	sv_killmonger01	 " , char: "	Killmonger	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	CommandStrong-	" },
{ id: "	sv_killmonger01_S01	 " , char: "	Erik Killmonger	 " , suit: "	블랙 팬더	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	CommandStrong-	" },
{ id: "	sv_kingpin01	 " , char: "	Kingpin	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandStrong-	" },
{ id: "	sv_kingpin01_S01	 " , char: "	Kingpin	 " , suit: "	시크릿 워즈: 아머 워즈	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandStrongMachine	" },
{ id: "	sv_korath01	 " , char: "	Korath	 " , suit: "	Marvel's 캡틴 마블	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilWeapon Master-	" },
{ id: "	sv_kraventhehunter01	 " , char: "	Kraven The Hunter	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityWeapon MasterSinister Six	" },
{ id: "	sv_lash01	 " , char: "	Lash	 " , suit: "	Marvel's 에이전트 오브 쉴.드.	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	ShieldEnergy Projection-	" },
{ id: "	sv_lash01_S01	 " , char: "	Lash	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Energy Projection--	" },
{ id: "	sv_lizard01	 " , char: "	Lizard	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Healing--	" },
{ id: "	sv_loki01	 " , char: "	Loki	 " , suit: "	Marvel's 어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AsgardChillMind	" },
{ id: "	sv_loki01_S01	 " , char: "	Loki	 " , suit: "	레이디 로키	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	ChillMind-	" },
{ id: "	sv_loki01_S02	 " , char: "	Loki	 " , suit: "	Marvel's 토르: 라그나로크	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AsgardChillMind	" },
{ id: "	sv_loki01_S03	 " , char: "	Loki	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	ChillMind-	" },
{ id: "	sv_magneto01	 " , char: "	Magneto	 " , suit: "	클래식	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Mind ResistEnergy Projection-	" },
{ id: "	sv_magneto01_S01	 " , char: "	Magneto	 " , suit: "	마블 나우!	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Mind ResistEnergy Projection-	" },
{ id: "	sv_magneto01_S02	 " , char: "	Magneto	 " , suit: "	하우스 오브 엑스	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Mind ResistEnergy Projection-	" },
{ id: "	sv_malekith01	 " , char: "	Malekith	 " , suit: "	Marvel's 토르: 다크 월드	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Pure Evil--	" },
{ id: "	sv_malekith01_S01	 " , char: "	Malekith	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Pure Evil--	" },
{ id: "	sv_maximus01	 " , char: "	Maximus	 " , suit: "	워 오브 킹즈	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Mind Resist--	" },
{ id: "	sv_mistersinister01	 " , char: "	Mister Fantastic	 " , suit: "	퓨처 파운데이션	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityLeadership-	" },
{ id: "	sv_modok01	 " , char: "	M.O.D.O.K.	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	MachineMind-	" },
{ id: "	sv_modok01_S01	 " , char: "	M.O.D.O.K.	 " , suit: "	스파이독	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Pure EvilMachineMind	" },
{ id: "	sv_modok01_S02	 " , char: "	M.O.D.O.K.	 " , suit: "	캡톡	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	MachineMind-	" },
{ id: "	sv_moltenman01	 " , char: "	Molten Man	 " , suit: "	Marvel's 스파이더맨: 파 프롬 홈	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilDurabilityFlame	" },
{ id: "	sv_morbius01	 " , char: "	Morbius	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "		" },
{ id: "	sv_morganlefay01	 " , char: "	Morgan Le Fay	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Magic--	" },
{ id: "	sv_mysterio01	 " , char: "	Mysterio	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Sinister Six--	" },
{ id: "	sv_mysterio01_S01	 " , char: "	Mysterio	 " , suit: "	Marvel's 스파이더맨: 파 프롬 홈	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	MindSinister Six-	" },
{ id: "	sv_mystique01	 " , char: "	Mystique	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Agility--	" },
{ id: "	sv_nebula01	 " , char: "	Nebula	 " , suit: "	Marvel's 가디언즈 오브 갤럭시	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	GuardiansWeapon MasterShock	" },
{ id: "	sv_nebula01_S01	 " , char: "	Nebula	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Shock--	" },
{ id: "	sv_nebula01_S02	 " , char: "	Nebula	 " , suit: "	Marvel's 어벤져스: 엔드게임	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon Master--	" },
{ id: "	sv_nebula01_S03	 " , char: "	Nebula	 " , suit: "	Marvel's 어벤져스: 엔드게임 (팀 슈트)	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon Master--	" },
{ id: "	sv_proximamidnight01	 " , char: "	Proxima Midnight	 " , suit: "	인피니티	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Fast Movement--	" },
{ id: "	sv_proximamidnight01_S01	 " , char: "	Proxima Midnight	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Black OrderFast MovementAgility	" },
{ id: "	sv_redguardian01	 " , char: "	Red Guardian	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityStrong-	" },
{ id: "	sv_redguardian01_S01	 " , char: "	Red Guardian	 " , suit: "	Marvel's 블랙 위도우	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityStrong-	" },
{ id: "	sv_redhulk01	 " , char: "	Red Hulk	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	DurabilityFlame-	" },
{ id: "	sv_redhulk01_S01	 " , char: "	Red Hulk	 " , suit: "	마블 나우!	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilityFlame-	" },
{ id: "	sv_redhulk01_S02	 " , char: "	Red Hulk	 " , suit: "	복수의 심비오트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	SymbioteFlame-	" },
{ id: "	sv_redskull01	 " , char: "	Red Skull	 " , suit: "	캡틴 아메리카: 퍼스트 어벤져	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	하이드라CommandPure Evil	" },
{ id: "	sv_redskull01_S01	 " , char: "	Red Skull	 " , suit: "	시크릿 워즈: 레드 스컬	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandPure Evil-	" },
{ id: "	sv_redskull01_S02	 " , char: "	Red Skull	 " , suit: "	하이드라 아머	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandPure EvilCosmic Cube	" },
{ id: "	sv_rhino01	 " , char: "	Rhino	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Strong--	" },
{ id: "	sv_ronan01	 " , char: "	Ronan	 " , suit: "	Marvel's 가디언즈 오브 갤럭시	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	GuardiansCommandMind Resist	" },
{ id: "	sv_ronan01_S01	 " , char: "	Ronan	 " , suit: "	어나힐레이션	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	CommandMind Resist-	" },
{ id: "	sv_ronan01_S02	 " , char: "	Ronan	 " , suit: "	Marvel's 캡틴 마블	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	GuardiansCommandMind Resist	" },
{ id: "	sv_sabretooth01	 " , char: "	Sabretooth	 " , suit: "	브라더후드 오브 뮤턴츠	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilAgility-	" },
{ id: "	sv_sabretooth01_S01	 " , char: "	Sabretooth	 " , suit: "	언캐니 어벤져스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilAgility-	" },
{ id: "	sv_sandman01	 " , char: "	Sandman	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	DurabilitySinister Six-	" },
{ id: "	sv_sentinel01	 " , char: "	Sentinel	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilMachine-	" },
{ id: "	sv_sentinel01_S01	 " , char: "	Sentinel	 " , suit: "	님로드 더 레서	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilMachine-	" },
{ id: "	sv_sin01	 " , char: "	Sin	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilWeapon Master-	" },
{ id: "	sv_skurge01	 " , char: "	Skurge	 " , suit: "	Marvel's 토르: 라그나로크	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	AsgardDurabilityStrong	" },
{ id: "	sv_stryfe01	 " , char: "	Stryfe	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionPure Evil-	" },
{ id: "	sv_supergiant01	 " , char: "	Supergiant	 " , suit: "	인피니티	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Mind ResistMind-	" },
{ id: "	sv_taskmaster01	 " , char: "	Taskmaster	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon MasterPure Evil-	" },
{ id: "	sv_taskmaster01_S01	 " , char: "	Taskmaster	 " , suit: "	Marvel's 블랙 위도우	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Weapon MasterPure Evil-	" },
{ id: "	sv_thane01	 " , char: "	Thane	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	StrongDurabilityPure Evil	" },
{ id: "	sv_thanos01	 " , char: "	Thanos	 " , suit: "	인피니티	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilDurabilityPower Cosmic	" },
{ id: "	sv_thanos01_S01	 " , char: "	Thanos	 " , suit: "	시크릿 워즈: 인피니티	 " , tier: "	3	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilDurabilityPower Cosmic	" },
{ id: "	sv_thanos01_S02	 " , char: "	Thanos	 " , suit: "	Marvel's 어벤져스: 인피니티 워	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilDurabilityPower Cosmic	" },
{ id: "	sv_thanos01_S03	 " , char: "	Thanos	 " , suit: "	Marvel's 어벤져스: 엔드게임	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilDurabilityPower Cosmic	" },
{ id: "	sv_titania01	 " , char: "	Titania	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Strong--	" },
{ id: "	sv_ulik01	 " , char: "	Ulik	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	DurabilityStrong-	" },
{ id: "	sv_ultron_boss01	 " , char: "	Ultron	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Pure EvilMachine-	" },
{ id: "	sv_ultron_boss01_S01	 " , char: "	Ultron Prime	 " , suit: "	Marvel's 어벤져스: 에이지 오브 울트론	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Pure EvilMachine-	" },
{ id: "	sv_ultron_boss01_S02	 " , char: "	Ultron Mark 1	 " , suit: "	Marvel's 어벤져스: 에이지 오브 울트론	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Pure EvilMachine-	" },
{ id: "	sv_ultron_boss01_S03	 " , char: "	Ultron Mark 3	 " , suit: "	Marvel's 어벤져스: 에이지 오브 울트론	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Pure EvilMachine-	" },
{ id: "	sv_ulyssesklaue01	 " , char: "	Ulysses Klaue	 " , suit: "	Marvel's 블랙 팬서	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon Master--	" },
{ id: "	sv_venom01	 " , char: "	Venom	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	SymbioteHealing-	" },
{ id: "	sv_venom01_S01	 " , char: "	Venom	 " , suit: "	시크릿 워즈: 마블 좀비스	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	SymbioteHealing-	" },
{ id: "	sv_venom01_S02	 " , char: "	Venom	 " , suit: "	Anti-Venom	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	SymbioteHealing-	" },
{ id: "	sv_victorious01	 " , char: "	Victorious	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Energy ProjectionFast Movement-	" },
{ id: "	sv_viper01	 " , char: "	Viper	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	Pure EvilPoison-	" },
{ id: "	sv_vulture01	 " , char: "	Vulture	 " , suit: "	클래식	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityFast MovementSinister Six	" },
{ id: "	sv_vulture01_S01	 " , char: "	Vulture	 " , suit: "	Marvel's 스파이더맨: 홈커밍	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgilityFast MovementSinister Six	" },
{ id: "	sv_whiplash01	 " , char: "	Whiplash	 " , suit: "	Marvel's 아이언맨 2	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	MachineShock-	" },
{ id: "	sv_yelenabelova01	 " , char: "	Yelena Belova	 " , suit: "	모던	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	sv_yelenabelova01_S01	 " , char: "	Yelena Belova	 " , suit: "	Marvel's 블랙 위도우	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	sv_yelenabelova01_S02	 " , char: "	Yelena Belova	 " , suit: "	Marvel's 블랙 위도우 (스노우 슈트)	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	Potential	 " , ability: "	AgentAgility-	" },
{ id: "	sv_yellowjacket01	 " , char: "	Yellowjacket	 " , suit: "	Marvel's 앤트맨	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	MachinePure Evil-	" },
{ id: "	sv_yellowjacket01_S01	 " , char: "	Yellowjacket	 " , suit: "	마블 나우!	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	MachinePure Evil-	" },
{ id: "	sv_yondu01	 " , char: "	Yondu	 " , suit: "	Marvel's 가디언즈 오브 갤럭시	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon MasterCommand-	" },
{ id: "	sv_yondu01_S01	 " , char: "	Yondu	 " , suit: "	올뉴, 올디퍼런트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon MasterCommand-	" },
{ id: "	sv_yondu01_S02	 " , char: "	Yondu	 " , suit: "	Marvel's 가디언즈 오브 갤럭시 Vol. 2	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	Weapon MasterCommand-	" },
{ id: "	boss_fenriswolf01	 " , char: "	Fenris Wolf	 " , suit: "	펜리르 울프	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	---	" },
{ id: "	boss_fenriswolf01_S01	 " , char: "	Fenris Wolf	 " , suit: "	펜리르 울프	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	---	" },
{ id: "	boss_frostbeast01	 " , char: "	Frost Beast	 " , suit: "	프로스트 비스트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	---	" },
{ id: "	boss_mbaku01	 " , char: "	M'Baku	 " , suit: "	Marvel's 블랙 팬서	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	---	" },
{ id: "	boss_mdigardserpent01	 " , char: "	Midgard Serpent	 " , suit: "	미드가르드 서펀트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	---	" },
{ id: "	boss_surtur01	 " , char: "	Surtur	 " , suit: "	수르트	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	---	" },
{ id: "	boss_talos01	 " , char: "	Talos	 " , suit: "	Marvel's 캡틴 마블	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	---	" },
{ id: "	boss_ymir01	 " , char: "	Ymir	 " , suit: "	이미르	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	---	" },
{ id: "	GM_Jocasta01	 " , char: "	Jocasta	 " , suit: "	조캐스타	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	---	" },
{ id: "	hero_melindamay01	 " , char: "	Melinda May	 " , suit: "	Marvel's 에이전트 오브 쉴.드.	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	---	" },
{ id: "	sv_devildinosaur01	 " , char: "	Devil Dinosaur	 " , suit: "	데빌 다이너소어	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	---	" },
{ id: "	hero_io01	 " , char: "	Io	 " , suit: "	이오	 " , tier: "	#	", name: "		", hei: "		 " , wei: "		 " , pot: "	#	 " , ability: "	---	" },

     
   ];

  event.preventDefault();
})
